<?php

use Illuminate\Database\Seeder;

class CenterTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('centers')->delete();
        $centers= array(
        array('name' => "Asociación para Evitar la Ceguera", 'short_name' => ""),
        array('name' => "CEMEV de Xalapa", 'short_name' => ""),
        array('name' => "Centro de Especialidades Médicas Dr. Rafael Lucio", 'short_name' => ""),
        array('name' => "Centro Dermatológico Pascua", 'short_name' => ""),
        array('name' => "Centro Hospitalario Sanatorio Durango", 'short_name' => ""),
        array('name' => "Centro Médico ABC", 'short_name' => ""),
        array('name' => "Centro Médico del Noroeste L. Donaldo Colosio, Hermosillo", 'short_name' => ""),
        array('name' => "Centro Médico del Noroeste UMAE No. 25, Monterrey", 'short_name' => ""),
        array('name' => "Centro Médico ISSEMyM Arturo Montiel Rojas", 'short_name' => ""),
        array('name' => "Centro Médico ISSEMyM Ecatepec", 'short_name' => ""),
        array('name' => "Centro Médico ISSEMyM Toluca", 'short_name' => ""),
        array('name' => "Centro Médico Lic. Adolfo López Mateos", 'short_name' => ""),
        array('name' => "Centro Médico Nacional 20 de Noviembre", 'short_name' => ""),
        array('name' => "Centro Médico Nacional Adolfo Ruiz Cortines, Veracruz", 'short_name' => ""),
        array('name' => "Centro Médico Nacional de Occidente", 'short_name' => ""),
        array('name' => "Centro Médico Nacional de Torreón", 'short_name' => ""),
        array('name' => "Centro Médico Nacional Dr. Manuel Ávila Camacho", 'short_name' => ""),
        array('name' => "Centro Médico Nacional La Raza H. Especialidades", 'short_name' => ""),
        array('name' => "Centro Médico Nacional La Raza H. General", 'short_name' => ""),
        array('name' => "Centro Médico Nacional No. 16", 'short_name' => ""),
        array('name' => "Centro Médico Nacional No. 25", 'short_name' => ""),
        array('name' => "Centro Médico Nacional No. 36", 'short_name' => ""),
        array('name' => "Centro Médico Nacional No. 48", 'short_name' => ""),
        array('name' => "Centro Médico Nacional Siglo XXI H. Especialidades", 'short_name' => ""),
        array('name' => "Centro Médico Nacional Siglo XXI H. General", 'short_name' => ""),
        array('name' => "Centro Médico Nacional Siglo XXI H. Pediatría", 'short_name' => ""),
        array('name' => "Centro Médico UMAE No. 14, Veracruz", 'short_name' => ""),
        array('name' => "Centro Médico UMAE No. 2, Cd. Obregón, Sonora", 'short_name' => ""),
        array('name' => "Centro Regional para la Prevenir de la Ceguera", 'short_name' => ""),
        array('name' => "Fundación Clínica Médica Sur", 'short_name' => ""),
        array('name' => "Fundación Hospital Nuestra Señora de la Luz", 'short_name' => ""),
        array('name' => "Fundación Universidad de Ciencias Bogota", 'short_name' => ""),
        array('name' => "Hospital Ángeles Clínica Londres", 'short_name' => ""),
        array('name' => "Hospital Ángeles de las Lomas", 'short_name' => ""),
        array('name' => "Hospital Ángeles del Pedregal", 'short_name' => ""),
        array('name' => "Hospital Ángeles Metropolitano", 'short_name' => ""),
        array('name' => "Hospital Angeles Mocel", 'short_name' => ""),
        array('name' => "Hospital Belisario Domínguez", 'short_name' => ""),
        array('name' => "Hospital Centenario Hospital Miguel Hidalgo", 'short_name' => ""),
        array('name' => "Hospital Central Cruz Roja Mexicana", 'short_name' => ""),
        array('name' => "Hospital Central de Chihuahua", 'short_name' => ""),
        array('name' => "Hospital Central Dr. I Morones Prieto, S L P", 'short_name' => ""),
        array('name' => "Hospital Central Militar", 'short_name' => ""),
        array('name' => "Hospital Central Norte Pemex", 'short_name' => ""),
        array('name' => "Hospital Central Regional de León", 'short_name' => ""),
        array('name' => "Hospital Central Sur de Alta Especialidad, Pemex", 'short_name' => ""),
        array('name' => "Hospital Central Universitario, Cd. Chihuahua", 'short_name' => ""),
        array('name' => "Hospital Christus Muguerza del Parque, Monterrey", 'short_name' => ""),
        array('name' => "Hospital Christus Murguerza Alta Especialidad, Monterrey", 'short_name' => ""),
        array('name' => "Hospital Christus Murguerza Alta Especialidad, Puebla", 'short_name' => ""),
        array('name' => "Hospital Civil de Culiacán, Sinaloa", 'short_name' => ""),
        array('name' => "Hospital Civil de Guadalajara Fray Antonio Alcalde", 'short_name' => ""),
        array('name' => "Hospital Civil de Tepic Nayarit Dr. A González Guevara", 'short_name' => ""),
        array('name' => "Hospital Civil Dr. A González Guevara", 'short_name' => ""),
        array('name' => "Hospital Civil Dr. Juan I. Menchaca", 'short_name' => ""),
        array('name' => "Hospital Darío Fernández", 'short_name' => ""),
        array('name' => "Hospital de Alta Espec Dr. Juan Graham Casasús", 'short_name' => ""),
        array('name' => "Hospital de Alta Espec Gustavo A. Rovirosa, Tabasco", 'short_name' => ""),
        array('name' => "Hospital de Concentración ISSEMyM Satélite", 'short_name' => ""),
        array('name' => "Hospital de Culiacán", 'short_name' => ""),
        array('name' => "Hospital de Especialidades del Bajio", 'short_name' => ""),
        array('name' => "Hospital de Especialidades del Niño y la Mujer", 'short_name' => ""),
        array('name' => "Hospital de Especialidades Dr. Bernardo Sepulveda", 'short_name' => ""),
        array('name' => "Hospital de Especialidades Monterrey", 'short_name' => ""),
        array('name' => "Hospital de Especialidades No. 25 CMN Noreste", 'short_name' => ""),
        array('name' => "Hospital de Especialidades No. 71 Torreón", 'short_name' => ""),
        array('name' => "Hospital de Especialidades Pediátricas", 'short_name' => ""),
        array('name' => "Hospital de Especialidades, Puebla", 'short_name' => ""),
        array('name' => "Hospital de Gineco-Pediatria No. 48", 'short_name' => ""),
        array('name' => "Hospital de Ginecoobstetricia No. 4", 'short_name' => ""),
        array('name' => "Hospital de la Mujer Ginequito", 'short_name' => ""),
        array('name' => "Hospital de la Mujer Morelia, Michoacán", 'short_name' => ""),
        array('name' => "Hospital de la Mujer y su familia, Monterrey", 'short_name' => ""),
        array('name' => "Hospital de la Mujer, México", 'short_name' => ""),
        array('name' => "Hospital de la Mujer, Puebla", 'short_name' => ""),
        array('name' => "Hospital de Niño y del Adolescente, Morelos", 'short_name' => ""),
        array('name' => "Hospital de Traumatología Victorio De la Fuente", 'short_name' => ""),
        array('name' => "Hospital de Traumatología y Ortopedia No. 21", 'short_name' => ""),
        array('name' => "Hospital del Niño DIF, Hidalgo", 'short_name' => ""),
        array('name' => "Hospital del Niño DIF, Puebla", 'short_name' => ""),
        array('name' => "Hospital del Niño IMIEM", 'short_name' => ""),
        array('name' => "Hospital del Niño Morelense", 'short_name' => ""),
        array('name' => "Hospital del Niño Poblano", 'short_name' => ""),
        array('name' => "Hospital del Niño Tabasco", 'short_name' => ""),
        array('name' => "Hospital Dr Fernando Quiroz", 'short_name' => ""),
        array('name' => "Hospital Dr. Rubén Leñero", 'short_name' => ""),
        array('name' => "Hospital Español de México", 'short_name' => ""),
        array('name' => "Hospital General  Balbuena", 'short_name' => ""),
        array('name' => "Hospital General Acapulco", 'short_name' => ""),
        array('name' => "Hospital General Aureliano Vadivieso", 'short_name' => ""),
        array('name' => "Hospital General de Atizapán", 'short_name' => ""),
        array('name' => "Hospital General de Campeche", 'short_name' => ""),
        array('name' => "Hospital General de Cd. Juárez", 'short_name' => ""),
        array('name' => "Hospital General de Cd. Victoria N. Treviño Zapata", 'short_name' => ""),
        array('name' => "Hospital General de Chiapas", 'short_name' => "HGDCh"),
        array('name' => "Hospital General de Cuautitlan", 'short_name' => "HGDCE"),
        array('name' => "Hospital General de Culiacán", 'short_name' => "HGDCU"),
        array('name' => "Hospital General de Durango", 'short_name' => ""),
        array('name' => "Hospital General de Ecatepec", 'short_name' => ""),
        array('name' => "Hospital General de Espec. Dr. J. Buenfil Osorio, Campeche", 'short_name' => ""),
        array('name' => "Hospital General de Hermosillo Sonora", 'short_name' => ""),
        array('name' => "Hospital General de León", 'short_name' => ""),
        array('name' => "Hospital General de Matamoros", 'short_name' => "HGDMa"),
        array('name' => "Hospital General de Mexicali", 'short_name' => "HGDMx"),
        array('name' => "Hospital General de México", 'short_name' => "HGDM"),
        array('name' => "Hospital General de Oaxaca", 'short_name' => "HGDOx"),
        array('name' => "Hospital General de Occidente", 'short_name' => "HGDOc"),
        array('name' => "Hospital General de Pachuca", 'short_name' => "HGDPa"),
        array('name' => "Hospital General de Puebla", 'short_name' => "HGDPu"),
        array('name' => "Hospital General de Querétaro", 'short_name' => ""),
        array('name' => "Hospital General de Reynosa, Tamaulipas", 'short_name' => ""),
        array('name' => "Hospital General de Saltillo", 'short_name' => "HGDSa"),
        array('name' => "Hospital General de Sonora", 'short_name' => "HGDSo"),
        array('name' => "Hospital General de Tampico", 'short_name' => "HGDTa"),
        array('name' => "Hospital General de Tlalnepantla Valle Ceylán", 'short_name' => ""),
        array('name' => "Hospital General de Toluca", 'short_name' => "HGDTo"),
        array('name' => "Hospital General de Veracruz", 'short_name' => ""),
        array('name' => "Hospital General de Zacatecas", 'short_name' => ""),
        array('name' => "Hospital General de Zona 1A Roberto Antonio de Mucha Macias", 'short_name' => ""),
        array('name' => "Hospital General de Zona No. 1, Durango", 'short_name' => ""),
        array('name' => "Hospital General de Zona No. 1, Saltillo", 'short_name' => ""),
        array('name' => "Hospital General de Zona No. 1, Tlaxcala", 'short_name' => ""),
        array('name' => "Hospital General de Zona No. 16, Torreón", 'short_name' => ""),
        array('name' => "Hospital General de Zona No. 33, Monterrey", 'short_name' => ""),
        array('name' => "Hospital General de Zona No. 36, Coatzacoalcos", 'short_name' => ""),
        array('name' => "Hospital General de Zona No. 4, Zamora Michoacán", 'short_name' => ""),
        array('name' => "Hospital General del Norte de Puebla", 'short_name' => ""),
        array('name' => "Hospital General del Sur de Puebla", 'short_name' => ""),
        array('name' => "Hospital General Dr. Agustín O´Horan, Yucatán", 'short_name' => ""),
        array('name' => "Hospital General Dr. Aurelio Valdivieso, Oaxaca", 'short_name' => ""),
        array('name' => "Hospital General Dr. Bernardo J. Gastelum", 'short_name' => ""),
        array('name' => "Hospital General Dr. Darío Fernández Fierro", 'short_name' => ""),
        array('name' => "Hospital General Dr. E. Vázquez Navarro, Puebla", 'short_name' => ""),
        array('name' => "Hospital general Dr. Enrique Cabrera", 'short_name' => ""),
        array('name' => "Hospital General Dr. Fernando Quiroz Gutiérrez", 'short_name' => ""),
        array('name' => "Hospital General Dr. Gustavo Baz Prada", 'short_name' => ""),
        array('name' => "Hospital General Dr. José G. Parres, Cuernavaca", 'short_name' => ""),
        array('name' => "Hospital General Dr. Manuel Gea González", 'short_name' => ""),
        array('name' => "Hospital General Dr. Miguel Silva, Morelia", 'short_name' => ""),
        array('name' => "Hospital General Dr. Salvador Zubiran Anchondo", 'short_name' => ""),
        array('name' => "Hospital General Ecatepec Dr José María Rodriguez", 'short_name' => ""),
        array('name' => "Hospital General Fernández Fierro", 'short_name' => ""),
        array('name' => "Hospital General Ignacio Morones Prieto", 'short_name' => ""),
        array('name' => "Hospital General Ignacio Zaragoza", 'short_name' => ""),
        array('name' => "Hospital General La Perla", 'short_name' => ""),
        array('name' => "Hospital General La Villa", 'short_name' => ""),
        array('name' => "Hospital General Las Américas, Ecatepec", 'short_name' => ""),
        array('name' => "Hospital General Naval de Alta especialidad", 'short_name' => ""),
        array('name' => "Hospital General No. 450, Durango", 'short_name' => ""),
        array('name' => "Hospital General Regional  No. 1", 'short_name' => ""),
        array('name' => "Hospital General Regional de León, Gto", 'short_name' => ""),
        array('name' => "Hospital General Regional Dr. Pascasio Gamboa, Chiapas", 'short_name' => ""),
        array('name' => "Hospital General Regional ISSSTE Veracruz", 'short_name' => ""),
        array('name' => "Hospital General Regional No. 1 Ignacio García Téllez, Mérida", 'short_name' => ""),
        array('name' => "Hospital General Regional No. 1 Vicente Guerrero,  Acapulco", 'short_name' => ""),
        array('name' => "Hospital General Regional No. 1, Cd. Obregón", 'short_name' => ""),
        array('name' => "Hospital General Regional No. 1, Chihuahua", 'short_name' => ""),
        array('name' => "Hospital General Regional No. 1, Culiacán", 'short_name' => ""),
        array('name' => "Hospital General Regional No. 1, Mc Gregor", 'short_name' => ""),
        array('name' => "Hospital General Regional No. 110 Gda", 'short_name' => ""),
        array('name' => "Hospital General Regional No. 17, Cancún", 'short_name' => ""),
        array('name' => "Hospital General Regional No. 196", 'short_name' => ""),
        array('name' => "Hospital General Regional No. 25", 'short_name' => ""),
        array('name' => "Hospital General Regional No. 36, Puebla", 'short_name' => ""),
        array('name' => "Hospital General Regional No. 46", 'short_name' => ""),
        array('name' => "Hospital General Regional No. 6 Cd. Madero", 'short_name' => ""),
        array('name' => "Hospital General Tacuba", 'short_name' => ""),
        array('name' => "Hospital General Ticomán", 'short_name' => ""),
        array('name' => "Hospital General Toluca", 'short_name' => ""),
        array('name' => "Hospital General Valentín Gómez Farias", 'short_name' => ""),
        array('name' => "Hospital General Zubiran Anchondo", 'short_name' => ""),
        array('name' => "Hospital Genral de Occidente", 'short_name' => ""),
        array('name' => "Hospital Gereral de Veracruz Dr. Rafael Lucio", 'short_name' => ""),
        array('name' => "Hospital Gral de Atizapán Dr. S González Herrejón", 'short_name' => ""),
        array('name' => "Hospital Infantil de Chihuahua", 'short_name' => ""),
        array('name' => "Hospital Infantil de México Dr. Federico Gómez", 'short_name' => ""),
        array('name' => "Hospital Infantil de Saltillo", 'short_name' => ""),
        array('name' => "Hospital Infantil de Sonora", 'short_name' => ""),
        array('name' => "Hospital Infantil de Tamaulipas", 'short_name' => ""),
        array('name' => "Hospital Infantil de Tlaxcala", 'short_name' => ""),
        array('name' => "Hospital Infantil del Edo de  Sonora", 'short_name' => ""),
        array('name' => "Hospital Infantil Privado", 'short_name' => ""),
        array('name' => "Hospital Juárez de México", 'short_name' => ""),
        array('name' => "Hospital Lic. Adolfo López Mateos", 'short_name' => ""),
        array('name' => "Hospital Materno Infantil", 'short_name' => ""),
        array('name' => "Hospital Materno Infantil ISSEMyM", 'short_name' => ""),
        array('name' => "Hospital Materno Infantil Toluca", 'short_name' => ""),
        array('name' => "Hospital Materno Perinatal, Edo de Mex", 'short_name' => ""),
        array('name' => "Hospital Médica Sur", 'short_name' => ""),
        array('name' => "Hospital Metropolitano Dr. Bernardo Sepúlveda, Monterrey", 'short_name' => ""),
        array('name' => "Hospital Naval", 'short_name' => ""),
        array('name' => "Hospital Nicolás San Juan", 'short_name' => ""),
        array('name' => "Hospital O'Haran", 'short_name' => ""),
        array('name' => "Hospital Pediátrico de Sinaloa", 'short_name' => ""),
        array('name' => "Hospital Pediátrico Tacubaya", 'short_name' => ""),
        array('name' => "Hospital Regional 1 de Octubre", 'short_name' => ""),
        array('name' => "Hospital Regional Culiacán", 'short_name' => ""),
        array('name' => "Hospital Regional de Alta Especialidad  Ciudad salud", 'short_name' => ""),
        array('name' => "Hospital Regional de Alta Especialidad de Oaxaca", 'short_name' => ""),
        array('name' => "Hospital Regional de Alta Especialidad de Veracruz", 'short_name' => ""),
        array('name' => "Hospital Regional de Alta Especialidad de Yucatán", 'short_name' => ""),
        array('name' => "Hospital Regional de Ciudad Victoria", 'short_name' => ""),
        array('name' => "Hospital Regional de Colima", 'short_name' => ""),
        array('name' => "Hospital Regional de Monterrey, Nuevo León", 'short_name' => ""),
        array('name' => "Hospital Regional de Pemex, Cd. Madero", 'short_name' => ""),
        array('name' => "Hospital Regional de Pemex, Salamanca", 'short_name' => ""),
        array('name' => "Hospital Regional de Tlalnepantla ISSEMyM", 'short_name' => ""),
        array('name' => "Hospital Regional Dr Rodolfo Nieto", 'short_name' => ""),
        array('name' => "Hospital Regional Dr. M Cárdenas De la Vega, Culiacán", 'short_name' => ""),
        array('name' => "Hospital Regional Dr. Valentín Gómez Farías, Guadalajara", 'short_name' => ""),
        array('name' => "Hospital Regional General Gómez Farías", 'short_name' => ""),
        array('name' => "Hospital Regional General Ignacio Zaragoza", 'short_name' => ""),
        array('name' => "Hospital Regional Ignacio Zaragoza", 'short_name' => ""),
        array('name' => "Hospital Regional ISSSTE Puebla", 'short_name' => ""),
        array('name' => "Hospital Regional Lic. Adolfo López Mateos", 'short_name' => ""),
        array('name' => "Hospital Regional Materno infantil de Alta Espec Nvo León", 'short_name' => ""),
        array('name' => "Hospital Regional Monterrey", 'short_name' => ""),
        array('name' => "Hospital Regional No. 1", 'short_name' => ""),
        array('name' => "Hospital Regional No. 1 Cd. Obregón, Sonora", 'short_name' => ""),
        array('name' => "Hospital Regional No. 1 Culiacán, Sin", 'short_name' => ""),
        array('name' => "Hospital Regional Rio Blanco Veracruz", 'short_name' => ""),
        array('name' => "Hospital Regional Universitario Colima", 'short_name' => ""),
        array('name' => "Hospital San José Tecnológico de Monterrey", 'short_name' => ""),
        array('name' => "Hospital Star Médica", 'short_name' => ""),
        array('name' => "Hospital Universitario de Burgos , España", 'short_name' => ""),
        array('name' => "Hospital Universitario de Puebla", 'short_name' => ""),
        array('name' => "Hospital Universitario de Saltillo", 'short_name' => ""),
        array('name' => "Hospital Universitario Dr.  A. Leaño", 'short_name' => ""),
        array('name' => "Hospital Universitario Dr. José Eleuterio González", 'short_name' => ""),
        array('name' => "Instituto Dermatológico Jaliscience", 'short_name' => ""),
        array('name' => "Instituto Jalisciense de Cirugia Reconstructiva", 'short_name' => ""),
        array('name' => "Instituto Materno Infantil del Estado de México", 'short_name' => ""),
        array('name' => "Instituto Nacional de Cancerología", 'short_name' => "INCan"),
        array('name' => "Instituto Nacional de Cardiología", 'short_name' => ""),
        array('name' => "Instituto Nacional de Ciencias Médicas y Nutricion Salvador Zuvirán", 'short_name' => ""),
        array('name' => "Instituto Nacional de Neurología y Neurocirugía", 'short_name' => ""),
        array('name' => "Instituto Nacional de Pediatría", 'short_name' => ""),
        array('name' => "Instituto Nacional de Perinatología", 'short_name' => "InNadePr"),
        array('name' => "Instituto Nacional de Rehabilitación", 'short_name' => ""),
        array('name' => "Instituto Oftalmológico Fundación Conde de Valenciana", 'short_name' => ""),
        array('name' => "Instituto Superior de Ciencias, Habana", 'short_name' => ""),
        array('name' => "Instituto Tecnológico de Estudios Superiores", 'short_name' => ""),
        array('name' => "ISSSTEP", 'short_name' => ""),
        array('name' => "Programa Multicéntrico Residencias Médicas", 'short_name' => ""),
        array('name' => "Sanatorio Durango", 'short_name' => ""),
        array('name' => "Secretaria de Salud del Distrito Federal", 'short_name' => ""),
        array('name' => "Swedish Medical Center", 'short_name' => ""),
        array('name' => "UMAE No. 1 León, Gto", 'short_name' => ""),
        array('name' => "UMAE No. 23 Dr. I Morones Prieto", 'short_name' => ""),
        array('name' => "UMAE No. 71 Torreón Coahuila", 'short_name' => ""),
        array('name' => "UMAE No.134 Torreón", 'short_name' => ""),
        array('name' => "UMAE No.167", 'short_name' => ""),
        array('name' => "Universidad Autónoma de Cd. Juárez", 'short_name' => ""),
        array('name' => "Universidad Autónoma de Nvo León", 'short_name' => ""),
        array('name' => "Universidad Autónoma de SLP", 'short_name' => ""),
        array('name' => "Universidad de Guadalajara", 'short_name' => ""),
        array('name' => "Universidad Nacional Autonóma de México", 'short_name' => "")
      );
        foreach ($centers as $item) {
            if ($item['short_name'] == "") {
                /*if(preg_match_all('/\b([A-Z0-9]{1,2})/',strtoupper($item['name']),$m)) {
                    $v = implode('',$m[1]); // $v is now SOQTU
                }
                $item['short_name'] = $v;
                */
                $item['short_name'] = createAcronym($item['name']);
            }
            $center = EMMA5\Center::create($item);
        }

        echo "Done";
    }
}
