<?php

use Illuminate\Database\Seeder;

class QuestionsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('questions')->delete();
        $questions = array(
        array('id' => '001','slot_id' => '1','order' => '1','text' => '1. El cuadro clínico es compatible con:'),
            array('id' => '002','slot_id' => '1','order' => '2','text' => '2. Para confirmar el diagnóstico se requiere:'),
            array('id' => '003','slot_id' => '1','order' => '3','text' => '3. La alteración en el sodio se explica por:'),
            array('id' => '004','slot_id' => '1','order' => '4','text' => '4. Esta alteración en el se corrige con:'),
            array('id' => '005','slot_id' => '1','order' => '5','text' => '5. Una complicación del tratamiento puede ser:'),
            array('id' => '006','slot_id' => '2','order' => '1','text' => '6. El mecanismo que explica esta hiponatremia es:'),
            array('id' => '007','slot_id' => '2','order' => '2','text' => '7. La corrección de Na en mEq/L en 24 horas NO debe exceder:'),
            array('id' => '008','slot_id' => '2','order' => '3','text' => '8. Se establece el diagnóstico con base a:'),
            array('id' => '009','slot_id' => '2','order' => '4','text' => '9. Otro dato que apoya el diagnóstico es:'),
            array('id' => '010','slot_id' => '2','order' => '5','text' => '10. El tratamiento inicial es:'),
            array('id' => '011','slot_id' => '3','order' => '1','text' => '11. El cuadro clínico es compatible con:'),
            array('id' => '012','slot_id' => '3','order' => '2','text' => '12. Al infundir solución fisiológica durante 4 horas empeora la hipokalemia, ésto se explica por:'),
            array('id' => '013','slot_id' => '3','order' => '3','text' => '13. La alteración que espera encontrar es:'),
            array('id' => '014','slot_id' => '3','order' => '4','text' => '14. El resultado de laboratorio que apoya el diagnóstico es:'),
            array('id' => '015','slot_id' => '3','order' => '5','text' => '15. El fármaco de primera elección que indica es:'),
            array('id' => '016','slot_id' => '4','order' => '1','text' => '16. El estudio inicial que solicita es:'),
            array('id' => '017','slot_id' => '4','order' => '2','text' => '17. La conducta inmediata es:'),
            array('id' => '018','slot_id' => '4','order' => '3','text' => '18. El efecto tóxico del potasio sobre el potencial de acción es:'),
            array('id' => '019','slot_id' => '4','order' => '4','text' => '19. En este paciente para obtener un balance negativo de potasio, indica:'),
            array('id' => '020','slot_id' => '4','order' => '5','text' => '20. A pesar de las medidas anteriores presenta oliguria, creatinina 4 mg/dL, BUN 80 y K 7.6 mEq/dL; la conducta a seguir es:'),
            array('id' => '021','slot_id' => '5','order' => '1','text' => '21. El diagnóstico más probable es:'),
            array('id' => '022','slot_id' => '5','order' => '2','text' => '22. Como apoyo diagnóstico solicita:'),
            array('id' => '023','slot_id' => '5','order' => '3','text' => '23. En este caso, la alteración histopatológica más probable es:'),
            array('id' => '024','slot_id' => '5','order' => '4','text' => '24. El tratamiento de la patología de base es:'),
            array('id' => '025','slot_id' => '5','order' => '5','text' => '25. En este paciente un factor adicional que disminuye la filtración glomerular es:'),
            array('id' => '026','slot_id' => '6','order' => '1','text' => '26. El diagnóstico más probable es:'),
            array('id' => '027','slot_id' => '6','order' => '2','text' => '27. Esta complicación se asocia a:'),
            array('id' => '028','slot_id' => '6','order' => '3','text' => '28. En este paciente el fármaco que CONTRAINDICA es:'),
            array('id' => '029','slot_id' => '6','order' => '4','text' => '29. El tratamiento inicial es:'),
            array('id' => '030','slot_id' => '6','order' => '5','text' => '30. El pronóstico es:'),
            array('id' => '031','slot_id' => '7','order' => '1','text' => '31. En este paciente el transporte peritoneal que sospecha es:'),
            array('id' => '032','slot_id' => '7','order' => '2','text' => '32. Para confirmar el tipo de transporte espera:'),
            array('id' => '033','slot_id' => '7','order' => '3','text' => '33. La modificación que indica a la prescripción es:'),
            array('id' => '034','slot_id' => '7','order' => '4','text' => '34. El dato más importante para esta modificación de prescripción es:'),
            array('id' => '035','slot_id' => '7','order' => '5','text' => '35. Una vez estabilizado, el KT/V semanal mínimo recomendado es:'),
            array('id' => '036','slot_id' => '8','order' => '1','text' => '36. El trasporte peritoneal es:'),
            array('id' => '037','slot_id' => '8','order' => '2','text' => '37. La modalidad de diálisis peritoneal que indica es:'),
            array('id' => '038','slot_id' => '8','order' => '3','text' => '38. La decisión anterior se fundamenta en:'),
            array('id' => '039','slot_id' => '8','order' => '4','text' => '39. En esta paciente la icodextrina NO se recomienda por:'),
            array('id' => '040','slot_id' => '8','order' => '5','text' => '40. En este caso la complicación a largo plazo que puede presentar con mayor frecuencia es:'),
            array('id' => '041','slot_id' => '9','order' => '1','text' => '41. El agente causal más probable es:'),
            array('id' => '042','slot_id' => '9','order' => '2','text' => '42. El tratamiento empírico de la peritonitis es:'),
            array('id' => '043','slot_id' => '9','order' => '3','text' => '43. Se confirma el agente causal más frecuente, se da tratamiento específico y es dada de alta. Regresa en 7 días con las mismas manifestaciones, la conducta a seguir es:'),
            array('id' => '044','slot_id' => '9','order' => '4','text' => '44. Se considera peritonitis refractaria a la falta de respuesta al tratamiento específico, después de cuántos días:'),
            array('id' => '045','slot_id' => '9','order' => '5','text' => '45. Por frecuencia el comportamiento del trasporte peritoneal en la peritonitis es:'),
            array('id' => '046','slot_id' => '10','order' => '1','text' => '46. La conducta a seguir es:'),
            array('id' => '047','slot_id' => '10','order' => '2','text' => '47. Para confirmar el diagnóstico de esta peritonitis requiere:'),
            array('id' => '048','slot_id' => '10','order' => '3','text' => '48. Debe iniciar tratamiento:'),
            array('id' => '049','slot_id' => '10','order' => '4','text' => '49. La complicación aguda asociada más frecuente es:'),
            array('id' => '050','slot_id' => '10','order' => '5','text' => '50. Se considera peritonitis recurrente ante:'),
            array('id' => '051','slot_id' => '11','order' => '1','text' => '51. El marcador nutricional es:'),
            array('id' => '052','slot_id' => '11','order' => '2','text' => '52. En este paciente la poca ingesta de alimentos se explica por:'),
            array('id' => '053','slot_id' => '11','order' => '3','text' => '53. El manejo que indica es:'),
            array('id' => '054','slot_id' => '11','order' => '4','text' => '54. La ingesta proteica (g/kg/día) que le recomienda es:'),
            array('id' => '055','slot_id' => '11','order' => '5','text' => '55. En caso de mala respuesta al manejo nutricional indica:'),
            array('id' => '056','slot_id' => '12','order' => '1','text' => '56. El diagnóstico es:'),
            array('id' => '057','slot_id' => '12','order' => '2','text' => '57. Lo que observa en la microscopia de luz es:'),
            array('id' => '058','slot_id' => '12','order' => '3','text' => '58. El fármaco de primera elección que adiciona a la prednisona es:'),
            array('id' => '059','slot_id' => '12','order' => '4','text' => '59. Los factores asociados con mal pronóstico son:'),
            array('id' => '060','slot_id' => '12','order' => '5','text' => '60. Este padecimiento se puede asociar a:'),
            array('id' => '061','slot_id' => '13','order' => '1','text' => '61. El diagnóstico más probable es:'),
            array('id' => '062','slot_id' => '13','order' => '2','text' => '62. En la imagen los depósitos característicos se localizan principalmente:'),
            array('id' => '063','slot_id' => '13','order' => '3','text' => '63. El tratamiento inicial es:'),
            array('id' => '064','slot_id' => '13','order' => '4','text' => '64. Esta patología se puede asociar con mayor frecuencia a:'),
            array('id' => '065','slot_id' => '13','order' => '5','text' => '65. En caso de trasplante:'),
            array('id' => '066','slot_id' => '14','order' => '1','text' => '66. El diagnóstico más probable es:'),
            array('id' => '067','slot_id' => '14','order' => '2','text' => '67. Lo que observa en la microscopia de luz es:'),
            array('id' => '068','slot_id' => '14','order' => '3','text' => '68. En la microscopia electrónica observa:'),
            array('id' => '069','slot_id' => '14','order' => '4','text' => '69. El tratamiento inicial es:'),
            array('id' => '070','slot_id' => '14','order' => '5','text' => '70. Ante la mala respuesta al tratamiento inicial indica:'),
            array('id' => '071','slot_id' => '15','order' => '1','text' => '71. El diagnóstico clínico más probable es:'),
            array('id' => '072','slot_id' => '15','order' => '2','text' => '72. Esta enfermedad se explica por:'),
            array('id' => '073','slot_id' => '15','order' => '3','text' => '73. El hallazgo histológico es:'),
            array('id' => '074','slot_id' => '15','order' => '4','text' => '74. El tratamiento inicial es:'),
            array('id' => '075','slot_id' => '15','order' => '5','text' => '75. Si la paciente evoluciona a IRC, el trasplante renal:'),
            array('id' => '076','slot_id' => '16','order' => '1','text' => '76. El diagnóstico es:'),
            array('id' => '077','slot_id' => '16','order' => '2','text' => '77. En esta patología se observa:'),
            array('id' => '078','slot_id' => '16','order' => '3','text' => '78. Se confirma el diagnóstico con la presencia de:'),
            array('id' => '079','slot_id' => '16','order' => '4','text' => '79. El tratamiento de elección es:'),
            array('id' => '080','slot_id' => '16','order' => '5','text' => '80. En general en esta patología el factor de mal pronóstico es:'),
            array('id' => '081','slot_id' => '17','order' => '1','text' => '81. El diagnóstico más probable es:'),
            array('id' => '082','slot_id' => '17','order' => '2','text' => '82. El factor de riesgo para el desarrollo de esta nefropatía es:'),
            array('id' => '083','slot_id' => '17','order' => '3','text' => '83. En esta nefropatía, los anticuerpos van dirigidos contra:'),
            array('id' => '084','slot_id' => '17','order' => '4','text' => '84. El marcador serológico específico en esta enfermedad es:'),
            array('id' => '085','slot_id' => '17','order' => '5','text' => '85. El tratamiento es:'),
            array('id' => '086','slot_id' => '18','order' => '1','text' => '86. El diagnóstico más probable es:'),
            array('id' => '087','slot_id' => '18','order' => '2','text' => '87. El mecanismo inmunológico de daño glomerular es:'),
            array('id' => '088','slot_id' => '18','order' => '3','text' => '88. El dato característico de esta patología es:'),
            array('id' => '089','slot_id' => '18','order' => '4','text' => '89. El tratamiento es:'),
            array('id' => '090','slot_id' => '18','order' => '5','text' => '90. A las 8 semanas de evolución, el complemento lo espera encontrar:'),
            array('id' => '091','slot_id' => '19','order' => '1','text' => '91. La alteración de la función renal probablemente se debe a:'),
            array('id' => '092','slot_id' => '19','order' => '2','text' => '92. Por frecuencia la causa más probable de la alteración en este paciente es:'),
            array('id' => '093','slot_id' => '19','order' => '3','text' => '93. El tratamiento es:'),
            array('id' => '094','slot_id' => '19','order' => '4','text' => '94. La complicación extrarrenal esperada más importante es:'),
            array('id' => '095','slot_id' => '19','order' => '5','text' => '95. En caso de realizar biopsia renal esperaría observar:'),
            array('id' => '096','slot_id' => '20','order' => '1','text' => '96. El diagnóstico más probable es:'),
            array('id' => '097','slot_id' => '20','order' => '2','text' => '97. En este momento el manejo específico es:'),
            array('id' => '098','slot_id' => '20','order' => '3','text' => '98. Esta patología se puede explicar por:'),
            array('id' => '099','slot_id' => '20','order' => '4','text' => '99. El dato inicial de buen pronóstico es:'),
            array('id' => '100','slot_id' => '20','order' => '5','text' => '100. El dato característico de la biopsia es:'),
            array('id' => '101','slot_id' => '21','order' => '1','text' => '101. El diagnóstico más probable es:'),
            array('id' => '102','slot_id' => '21','order' => '2','text' => '102. En este padecimiento en la biopsia renal se observa:'),
            array('id' => '103','slot_id' => '21','order' => '3','text' => '103. El estudio inmunológico que apoya el diagnóstico con mayor frecuencia es:'),
            array('id' => '104','slot_id' => '21','order' => '4','text' => '104. El tratamiento es esteroide más:'),
            array('id' => '105','slot_id' => '21','order' => '5','text' => '105. NO responde al tratamiento y se decide iniciar hemodiálisis y administrar:'),
            array('id' => '106','slot_id' => '22','order' => '1','text' => '106. En esta paciente los niveles de complemento esperados son:'),
            array('id' => '107','slot_id' => '22','order' => '2','text' => '107. En la biopsia renal espera observar:'),
            array('id' => '108','slot_id' => '22','order' => '3','text' => '108. El tratamiento es:'),
            array('id' => '109','slot_id' => '22','order' => '4','text' => '109. El tratamiento para las alteraciones de la coagulación es:'),
            array('id' => '110','slot_id' => '22','order' => '5','text' => '110. Para el estudio inicial de la anemia solicita:'),
            array('id' => '111','slot_id' => '23','order' => '1','text' => '111. El diagnóstico más probable es:'),
            array('id' => '112','slot_id' => '23','order' => '2','text' => '112. Para confirmar la enfermedad de base el estudio que solicita es:'),
            array('id' => '113','slot_id' => '23','order' => '3','text' => '113. La lesión histopatológica sugestiva del diagnóstico es:'),
            array('id' => '114','slot_id' => '23','order' => '4','text' => '114. El tratamiento es:'),
            array('id' => '115','slot_id' => '23','order' => '5','text' => '115. El tratamiento debe incluir:'),
            array('id' => '116','slot_id' => '24','order' => '1','text' => '116. El diagnóstico más probable es:'),
            array('id' => '117','slot_id' => '24','order' => '2','text' => '117. Esta enfermedad se relaciona con:'),
            array('id' => '118','slot_id' => '24','order' => '3','text' => '118. La imagen histopatológica característica es:'),
            array('id' => '119','slot_id' => '24','order' => '4','text' => '119. Un factor de mal pronóstico es:'),
            array('id' => '120','slot_id' => '24','order' => '5','text' => '120. Por frecuencia la complicación que se puede asociar es:'),
            array('id' => '121','slot_id' => '25','order' => '1','text' => '121. El defecto de la enfermedad se encuentra en:'),
            array('id' => '122','slot_id' => '25','order' => '2','text' => '122. En la imagen observa:'),
            array('id' => '123','slot_id' => '25','order' => '3','text' => '123. En la inmunofluorescencia la alteración que se puede observar es:'),
            array('id' => '124','slot_id' => '25','order' => '4','text' => '124. La forma de transmisión genética más frecuente de esta patología es:'),
            array('id' => '125','slot_id' => '25','order' => '5','text' => '125. Un estudio de apoyo diagnóstico es biopsia de:'),
            array('id' => '126','slot_id' => '26','order' => '1','text' => '126. El diagnóstico probable es enfermedad de:'),
            array('id' => '127','slot_id' => '26','order' => '2','text' => '127. En la biopsia renal se observan depósitos de:'),
            array('id' => '128','slot_id' => '26','order' => '3','text' => '128. La forma de transmisión de esta enfermedad es:'),
            array('id' => '129','slot_id' => '26','order' => '4','text' => '129. El tratamiento es:'),
            array('id' => '130','slot_id' => '26','order' => '5','text' => '130. La evolución natural de la enfermedad es :'),
            array('id' => '131','slot_id' => '27','order' => '1','text' => '131. El diagnóstico más probable es:'),
            array('id' => '132','slot_id' => '27','order' => '2','text' => '133. Las manifestaciones clínicas de esta enfermedad reflejan una alteración en:'),
            array('id' => '133','slot_id' => '27','order' => '3','text' => '134. La alteración extrarrenal que debe investigar es:'),
            array('id' => '134','slot_id' => '27','order' => '4','text' => '135. La imagen histológica característica es:'),
            array('id' => '135','slot_id' => '27','order' => '5','text' => 'El paciente recibió trasplante renal, la evolución esperada es:'),
            array('id' => '136','slot_id' => '28','order' => '1','text' => '136. El diagnóstico probable es:'),
            array('id' => '137','slot_id' => '28','order' => '2','text' => '137. El estudio que confirma el diagnóstico es:'),
            array('id' => '138','slot_id' => '28','order' => '3','text' => '138. En este momento el tratamiento de primera elección es:'),
            array('id' => '139','slot_id' => '28','order' => '4','text' => '139. A largo plazo la complicación más frecuente que puede presentar es:'),
            array('id' => '140','slot_id' => '28','order' => '5','text' => '140. El mecanismo que explica la complicación anterior es:'),
            array('id' => '141','slot_id' => '29','order' => '1','text' => '141. El cuadro clínico es compatible con:'),
            array('id' => '142','slot_id' => '29','order' => '2','text' => '142. La insuficiencia renal está condicionada por:'),
            array('id' => '143','slot_id' => '29','order' => '3','text' => '143. En este momento el manejo es:'),
            array('id' => '144','slot_id' => '29','order' => '4','text' => '144. En el ultrasonido renal espera observar:'),
            array('id' => '145','slot_id' => '29','order' => '5','text' => '145. De NO resolverse el problema, la complicación esperada es:'),
            array('id' => '146','slot_id' => '30','order' => '1','text' => '146. El diagnóstico más probable es:'),
            array('id' => '147','slot_id' => '30','order' => '2','text' => '147. La lesión que espera en la biopsia renal es:'),
            array('id' => '148','slot_id' => '30','order' => '3','text' => '148. El manejo en este momento es:'),
            array('id' => '149','slot_id' => '30','order' => '4','text' => '149. En la tomografía computarizada de control espera observar:'),
            array('id' => '150','slot_id' => '30','order' => '5','text' => '150. En esta enfermedad se puede presentar:'),
            array('id' => '151','slot_id' => '31','order' => '1','text' => '151. La fisiopatología más aceptada para la presentación de la preeclampsia es:'),
            array('id' => '152','slot_id' => '31','order' => '2','text' => '152. En esta paciente la lesión glomerular que se puede presentar es:'),
            array('id' => '153','slot_id' => '31','order' => '3','text' => '153. La complicación a largo plazo más frecuente que puede presentar la madre es:'),
            array('id' => '154','slot_id' => '31','order' => '4','text' => '154. Este producto puede presentar:'),
            array('id' => '155','slot_id' => '31','order' => '5','text' => '155. El factor de riesgo para presentar preeclampsia es:'),
            array('id' => '156','slot_id' => '32','order' => '1','text' => '156. La causa más probable de este síndrome nefrótico es:'),
            array('id' => '157','slot_id' => '32','order' => '2','text' => '157. La primera acción es:'),
            array('id' => '158','slot_id' => '32','order' => '3','text' => '158. El principal factor de riesgo para pérdida fetal es:'),
            array('id' => '159','slot_id' => '32','order' => '4','text' => '159. Indica diuréticos en caso de:'),
            array('id' => '160','slot_id' => '32','order' => '5','text' => '160. Confirma su diagnóstico, la conducta inicial a seguir es:'),
            array('id' => '161','slot_id' => '33','order' => '1','text' => '161. El cuadro clínico sugiere:'),
            array('id' => '162','slot_id' => '33','order' => '2','text' => '162. El estudio para confirmar el diagnóstico es:'),
            array('id' => '163','slot_id' => '33','order' => '3','text' => '163. El tratamiento es:'),
            array('id' => '164','slot_id' => '33','order' => '4','text' => '164. La lesión en esta paciente se relaciona con:'),
            array('id' => '165','slot_id' => '33','order' => '5','text' => '165. El acceso vascular de primera elección en todo paciente en hemodiálisis es:'),
            array('id' => '166','slot_id' => '34','order' => '1','text' => '166. El cuadro es compatible con hipertensión:'),
            array('id' => '167','slot_id' => '34','order' => '2','text' => '167. El cuadro actual se explica por:'),
            array('id' => '168','slot_id' => '34','order' => '3','text' => '168. El tratamiento es:'),
            array('id' => '169','slot_id' => '34','order' => '4','text' => '169. El régimen dietético inicial que indica es:'),
            array('id' => '170','slot_id' => '34','order' => '5','text' => '170. Una contraindicación relativa de trasplante es:'),
            array('id' => '171','slot_id' => '35','order' => '1','text' => '171. El manejo inicial es:'),
            array('id' => '172','slot_id' => '35','order' => '2','text' => '172. La medida de prevención que debe instalar en la unidad de hemodiálisis es:'),
            array('id' => '173','slot_id' => '35','order' => '3','text' => '173. El factor que indica mal pronóstico es:'),
            array('id' => '174','slot_id' => '35','order' => '4','text' => '174. La evolución más probable es hacia:'),
            array('id' => '175','slot_id' => '35','order' => '5','text' => '175. Para decidir transplante renal, el estudio que le proporciona mayor información es:'),
            array('id' => '176','slot_id' => '36','order' => '1','text' => '176. El tratamiento de primera elección es:'),
            array('id' => '177','slot_id' => '36','order' => '2','text' => '177. La selección del tratamiento anterior lo fundamenta principalmente en:'),
            array('id' => '178','slot_id' => '36','order' => '3','text' => '178. La complicación por el uso de citrato es:'),
            array('id' => '179','slot_id' => '36','order' => '4','text' => '179. La ventaja de utilizar citrato en vez de bicarbonato es:'),
            array('id' => '180','slot_id' => '36','order' => '5','text' => '180. Para aumentar la eficiencia de la remoción de solutos se requiere:'),
            array('id' => '181','slot_id' => '37','order' => '1','text' => '181. La anemia se puede explicar por:'),
            array('id' => '182','slot_id' => '37','order' => '2','text' => '182. El tratamiento de esta anemia es:'),
            array('id' => '183','slot_id' => '37','order' => '3','text' => '183. De acuerdo con KDIGO en esta paciente el rango en g/dL recomendado de hemoglobina debe ser:'),
            array('id' => '184','slot_id' => '37','order' => '4','text' => '184. Continua con anemia, la falta de respuesta se explica por:'),
            array('id' => '185','slot_id' => '37','order' => '5','text' => '185. La siguiente conducta a seguir es:'),
            array('id' => '186','slot_id' => '38','order' => '1','text' => '186. Con los resultados del panel viral para hepatitis se puede concluir que la paciente:'),
            array('id' => '187','slot_id' => '38','order' => '2','text' => '187. En esta paciente las alteraciones hepáticas se deben a:'),
            array('id' => '188','slot_id' => '38','order' => '3','text' => '188. Para confirmar la enfermedad hepática solicita:'),
            array('id' => '189','slot_id' => '38','order' => '4','text' => '189. En esta paciente el factor de mal pronóstico sería:'),
            array('id' => '190','slot_id' => '38','order' => '5','text' => '190. En esta paciente el tratamiento es:'),
            array('id' => '191','slot_id' => '39','order' => '1','text' => '191. El diagnóstico más probable es:'),
            array('id' => '192','slot_id' => '39','order' => '2','text' => '192. El estudio inicial que le proporciona mayor información diagnostica es determinación de:'),
            array('id' => '193','slot_id' => '39','order' => '3','text' => '193. El estudio de imagen que ayuda a definir el diagnóstico es:'),
            array('id' => '194','slot_id' => '39','order' => '4','text' => '194. El tratamiento de elección es:'),
            array('id' => '195','slot_id' => '39','order' => '5','text' => '195. El fármaco que puede interferir con el diagnóstico es:'),
            array('id' => '196','slot_id' => '40','order' => '1','text' => '196. El tratamiento inmediato de primera elección es:'),
            array('id' => '197','slot_id' => '40','order' => '2','text' => '197. El valor que debe de disminuir la presión arterial en los siguientes 60 minutos es:'),
            array('id' => '198','slot_id' => '40','order' => '3','text' => '198. En esta paciente la complicación de la crisis hipertensiva es:'),
            array('id' => '199','slot_id' => '40','order' => '4','text' => '199. El tratamiento antihipertensivo de elección puede causar:'),
            array('id' => '200','slot_id' => '40','order' => '5','text' => '200. Una vez controlada la emergencia hipertensiva; la conducta a seguir es:'),
            array('id' => '201','slot_id' => '41','order' => '1','text' => '201. El diagnóstico clínico más probable es:'),
            array('id' => '202','slot_id' => '41','order' => '2','text' => '202. La prueba diagnóstica más útil es:'),
            array('id' => '203','slot_id' => '41','order' => '3','text' => '203. Otro estudio de apoyo diagnóstico que solicita es:'),
            array('id' => '204','slot_id' => '41','order' => '4','text' => '204. El estudio anterior NO es concluyente, el siguiente paso es solicitar:'),
            array('id' => '205','slot_id' => '41','order' => '5','text' => '205. El tratamiento de elección es:'),
            array('id' => '206','slot_id' => '42','order' => '1','text' => '206. En este caso la lesión que se asocia con mayor frecuencia es:'),
            array('id' => '207','slot_id' => '42','order' => '2','text' => '207. El procedimiento con mayor sensibilidad y especificidad para confirmar el diagnóstico es:'),
            array('id' => '208','slot_id' => '42','order' => '3','text' => '208. En este caso el fármaco que tiene mayor riesgo de disminuir la filtración glomerular es:'),
            array('id' => '209','slot_id' => '42','order' => '4','text' => '209. El tratamiento es:'),
            array('id' => '210','slot_id' => '42','order' => '5','text' => '210. La complicación que se puede presentar en esta patología es:'),
            array('id' => '211','slot_id' => '43','order' => '1','text' => '211. El diagnóstico probable es:'),
            array('id' => '212','slot_id' => '43','order' => '2','text' => '212. Para el estudio inicial de la paciente indica:'),
            array('id' => '213','slot_id' => '43','order' => '3','text' => '213. El estudio para confirmar el diagnóstico es:'),
            array('id' => '214','slot_id' => '43','order' => '4','text' => '214. Un mecanismo fisiopatológico de la hipertensión es:'),
            array('id' => '215','slot_id' => '43','order' => '5','text' => '215. El tratamiento de primera elección es:'),
            array('id' => '216','slot_id' => '44','order' => '1','text' => '216. La causa más probable del daño renal agudo es:'),
            array('id' => '217','slot_id' => '44','order' => '2','text' => '217. Un dato que apoya al diagnóstico es:'),
            array('id' => '218','slot_id' => '44','order' => '3','text' => '218. El factor que se encuentra asociado al mal pronóstico de la función renal es:'),
            array('id' => '219','slot_id' => '44','order' => '4','text' => '219. El tratamiento de primera elección es:'),
            array('id' => '220','slot_id' => '44','order' => '5','text' => '220. En caso de NO existir respuesta con el manejo inicial recomendaría:'),
            array('id' => '221','slot_id' => '45','order' => '1','text' => '222. La falla renal es secundaria a:'),
            array('id' => '222','slot_id' => '45','order' => '2','text' => '221. El mecanismo más probable de la hipocalemia es:'),
            array('id' => '223','slot_id' => '45','order' => '3','text' => '223. La lesión histológica caracteristica es:'),
            array('id' => '224','slot_id' => '45','order' => '4','text' => '224. Esta patología se debe a:'),
            array('id' => '225','slot_id' => '45','order' => '5','text' => '225. La conducta inicial es:'),
            array('id' => '226','slot_id' => '46','order' => '1','text' => '226. La prueba más sensible es:'),
            array('id' => '227','slot_id' => '46','order' => '2','text' => '227. La lesión más probable es:'),
            array('id' => '228','slot_id' => '46','order' => '3','text' => '228. El factor de riesgo más probable para el desarrollo del daño renal es:'),
            array('id' => '229','slot_id' => '46','order' => '4','text' => '229. Para prevenir el riesgo de nefrotoxicidad utiliza:'),
            array('id' => '230','slot_id' => '46','order' => '5','text' => '230. La evolución más probable es:'),
            array('id' => '231','slot_id' => '47','order' => '1','text' => '231. El diagnóstico probable es:'),
            array('id' => '232','slot_id' => '47','order' => '2','text' => '232. La causa más probable es:'),
            array('id' => '233','slot_id' => '47','order' => '3','text' => '233. El estudio de apoyo diagnóstico de primera elección es:'),
            array('id' => '234','slot_id' => '47','order' => '4','text' => '234. El manejo inicial es:'),
            array('id' => '235','slot_id' => '47','order' => '5','text' => '235. El pronóstico es:'),
            array('id' => '236','slot_id' => '48','order' => '1','text' => '236. El manejo inmediato es:'),
            array('id' => '237','slot_id' => '48','order' => '2','text' => '237. La siguiente acción es:'),
            array('id' => '238','slot_id' => '48','order' => '3','text' => '238. Para la corrección de la anemia, a largo plazo se recomienda mantener la ferritina:'),
            array('id' => '239','slot_id' => '48','order' => '4','text' => '239. Con los niveles de hormona paratiroidea, el diagnóstico que puede integrar es:'),
            array('id' => '240','slot_id' => '48','order' => '5','text' => '240. De acuerdo a la cifra de PTH y de PO<sub>4</sub>, el tratamiento inicial es:'),
            array('id' => '241','slot_id' => '49','order' => '1','text' => '241. El indicador más útil para valorar estado nutricional actual es:'),
            array('id' => '242','slot_id' => '49','order' => '2','text' => '242. El antihipertensivo que proporciona mejores resultados es:'),
            array('id' => '243','slot_id' => '49','order' => '3','text' => '243. La meta de hemoglobina glucosilada es:'),
            array('id' => '244','slot_id' => '49','order' => '4','text' => '244. Los g/kg/día mínimos de proteínas de alto valor biológico que indica en la dieta son:'),
            array('id' => '245','slot_id' => '49','order' => '5','text' => '245. La hipercolesterolemia la trata con:'),
            array('id' => '246','slot_id' => '50','order' => '1','text' => 'La combinación IECA y ARA:'),
            array('id' => '247','slot_id' => '50','order' => '2','text' => 'El punto de corte en mL/min/año para establecer progresión rápida es:'),
            array('id' => '248','slot_id' => '50','order' => '3','text' => 'Si la paciente tiene progresión rápida de la ERC la indicación es:'),
            array('id' => '249','slot_id' => '50','order' => '4','text' => 'En el último mes desarrolla síndrome nefrótico, el estudio que indica es:'),
            array('id' => '250','slot_id' => '50','order' => '5','text' => 'Disminuye Hb a 9.5 g/dL, se le administra hierro IV y eritropoyetina. Un mes mas tarde se duplica la dosis inicial de eritropoyetina con lo que aumenta la Hb a 9.9 g/dL. La conducta a seguir es:'),
            array('id' => '251','slot_id' => '51','order' => '1','text' => '251. En este paciente la composición más probable del lito es:'),
            array('id' => '252','slot_id' => '51','order' => '2','text' => '252. La causa metabólica es:'),
            array('id' => '253','slot_id' => '51','order' => '3','text' => '253. Para determinar la causa metabólica solicita:'),
            array('id' => '254','slot_id' => '51','order' => '4','text' => '254. El siguiente estudio que solicita es:'),
            array('id' => '255','slot_id' => '51','order' => '5','text' => '255. El tratamiento es:'),
            array('id' => '256','slot_id' => '52','order' => '1','text' => '256. Las imágenes hipodensas del riñón izquierdo tienen un coeficiente de absorción de 300 UH; el diagnóstico probable es:'),
            array('id' => '257','slot_id' => '52','order' => '2','text' => '257. Es frecuente en esta patología encontrar:'),
            array('id' => '258','slot_id' => '52','order' => '3','text' => '258. Esta patología se asocia con mayor frecuencia a:'),
            array('id' => '259','slot_id' => '52','order' => '4','text' => '259. Los gérmenes que con mayor frecuencia producen esta patología son:'),
            array('id' => '260','slot_id' => '52','order' => '5','text' => '260. El tratamiento inicial es:'),
            array('id' => '261','slot_id' => '53','order' => '1','text' => '261. Un efecto del control de la hiperglucemia es:'),
            array('id' => '262','slot_id' => '53','order' => '2','text' => '262. Recomienda determinar albuminuria:'),
            array('id' => '263','slot_id' => '53','order' => '3','text' => '263. La albuminuria moderada se debe a:'),
            array('id' => '264','slot_id' => '53','order' => '4','text' => '264. La primera acción es:'),
            array('id' => '265','slot_id' => '53','order' => '5','text' => '265. El manejo de la albuminuria incluye:'),
            array('id' => '266','slot_id' => '54','order' => '1','text' => '266. La paciente se encuentra en un estadio de enfermedad renal:'),
            array('id' => '267','slot_id' => '54','order' => '2','text' => '267. El mecanismo nefroprotector de los IECA es:'),
            array('id' => '268','slot_id' => '54','order' => '3','text' => '268. El efecto adverso del hipoglucemiante utilizado es:'),
            array('id' => '269','slot_id' => '54','order' => '4','text' => '269. De estos fármacos el que disminuye la albuminuria y fibrosis tubulointersticial es:'),
            array('id' => '270','slot_id' => '54','order' => '5','text' => '270. El tratamiento de elección de la dislipidemia es:'),
            array('id' => '271','slot_id' => '55','order' => '1','text' => '271. El cuadro clínico es compatible con infección por:'),
            array('id' => '272','slot_id' => '55','order' => '2','text' => '272. El estudio inicial que solicita es:'),
            array('id' => '273','slot_id' => '55','order' => '3','text' => '273. Para confirmar el diagnóstico solicita:'),
            array('id' => '274','slot_id' => '55','order' => '4','text' => '274. El tratamiento que indica es:'),
            array('id' => '275','slot_id' => '55','order' => '5','text' => '275. El efecto adverso más frecuente del tratamiento es:'),
            array('id' => '276','slot_id' => '56','order' => '1','text' => '276. El diagnóstico más probable es:'),
            array('id' => '277','slot_id' => '56','order' => '2','text' => '277. Para confirmar el diagnóstico se requiere:'),
            array('id' => '278','slot_id' => '56','order' => '3','text' => '278. El tratamiento es:'),
            array('id' => '279','slot_id' => '56','order' => '4','text' => '279. La vigilancia de la respuesta al tratamiento la realiza mediante:'),
            array('id' => '280','slot_id' => '56','order' => '5','text' => '280. Con el tratamiento adecuado la evolución esperada es:'),
            array('id' => '281','slot_id' => '57','order' => '1','text' => '281. La indicación correcta es:'),
            array('id' => '282','slot_id' => '57','order' => '2','text' => '282. El mayor riesgo teratogénico es con:'),
            array('id' => '283','slot_id' => '57','order' => '3','text' => '283. En caso de embarazo, la complicación fetal más probable con mofetil micofenolato sería:'),
            array('id' => '284','slot_id' => '57','order' => '4','text' => '284. Un embarazo se podría permitir ante:'),
            array('id' => '285','slot_id' => '57','order' => '5','text' => '285. En esta paciente la complicación gestacional más frecuente será:'),
            array('id' => '286','slot_id' => '58','order' => '1','text' => '286. El diagnóstico más probable es:'),
            array('id' => '287','slot_id' => '58','order' => '2','text' => '287. El dato característico de la biopsia es:'),
            array('id' => '288','slot_id' => '58','order' => '3','text' => '288. De acuerdo a la imagen de la biopsia y a la falta de respuesta, el tratamiento es:'),
            array('id' => '289','slot_id' => '58','order' => '4','text' => '289. Para el seguimiento solicita:'),
            array('id' => '290','slot_id' => '58','order' => '5','text' => '290. La evolución esperada de este paciente a largo plazo es:'),
            array('id' => '291','slot_id' => '59','order' => '1','text' => '292. La brecha aniónica urinaria es:'),
            array('id' => '292','slot_id' => '59','order' => '2','text' => '293. La excreción neta de ácidos es de 42 y la brecha aniónica urinaria sugieren que la paciente cursa con:'),
            array('id' => '293','slot_id' => '59','order' => '3','text' => '294. Esta enfermedad se caracteriza por:'),
            array('id' => '294','slot_id' => '59','order' => '4','text' => '295. El resultado de la brecha aniónica urinaria en esta paciente, indica que existe:'),
            array('id' => '295','slot_id' => '59','order' => '5','text' => 'La complicación más frecuente que puede presentar es:'),
            array('id' => '296','slot_id' => '60','order' => '1','text' => 'Este trastorno ocurre con mayor frecuencia en pacientes :'),
            array('id' => '297','slot_id' => '60','order' => '2','text' => 'El diagnóstico del trastorno acido base es:'),
            array('id' => '298','slot_id' => '60','order' => '3','text' => 'Los niveles de renina y aldosterona que espera son:'),
            array('id' => '299','slot_id' => '60','order' => '4','text' => 'La causa más probable de este cuadro clínico es:'),
            array('id' => '300','slot_id' => '60','order' => '5','text' => 'El trastorno del estado acido base se debe principalmente a:')
        );

        foreach ($questions as $question) {
            EMMA5\Question::create($question);
        }
    }
}
