<?php

use Illuminate\Database\Seeder;

class QuestionsTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        //
        $faker = Faker\Factory::create();
        DB::table('subjects')->delete();
        DB::table('slots')->delete();
        DB::table('vignettes')->delete();
        DB::table('questions')->delete();
        DB::table('distractors')->delete();

        $subjects = array(
            array('text' => 'Alteración hidroelectrólica y ácido-base','id' => '001'),
            array('text' => 'Enfermedad renal y cáncer','id' => '002'),
            array('text' => 'Diálisis peritoneal','id' => '003'),
            array('text' => 'Enfermedades glomerulares primarias','id' => '004'),
            array('text' => 'Enfermedades glomerulares secundarias','id' => '005'),
            array('text' => 'Enfermedades hereditarias-congénitas','id' => '006'),
            array('text' => 'Enfermedad renal obstructiva','id' => '007'),
            array('text' => 'Enfermedad renal y embarazo','id' => '008'),
            array('text' => 'Hemodiálisis','id' => '009'),
            array('text' => 'Hipertensión arterial','id' => '010'),
            array('text' => 'Insuficiencia renal aguda','id' => '011'),
            array('text' => 'Enfermedad renal crónica','id' => '012'),
            array('text' => 'Litiasis renal','id' => '013'),
            array('text' => 'Nefropatía diabética','id' => '014'),
            array('text' => 'Trasplante renal','id' => '015'),
            array('text' => 'Tubulopatías','id' => '016')
        );

        foreach ($subjects as $subject) {
            EMMA5\Subject::create($subject);
        }


        $slots = array(
                array("id" => "001", "subject_id" => "1", "order" => "001", "instructions" => "Responda el siguiente caso clínico"),
                array("id" => "002", "subject_id" => "1", "order" => "002", "instructions" => "Responda el siguiente caso clínico"),
                array("id" => "003", "subject_id" => "1", "order" => "003", "instructions" => "Responda el siguiente caso clínico"),
                array("id" => "004", "subject_id" => "1", "order" => "004", "instructions" => "Responda el siguiente caso clínico"),
                array("id" => "005", "subject_id" => "2", "order" => "005", "instructions" => "Responda el siguiente caso clínico"),
                array("id" => "006", "subject_id" => "3", "order" => "006", "instructions" => "Responda el siguiente caso clínico"),
                array("id" => "007", "subject_id" => "3", "order" => "007", "instructions" => "Responda el siguiente caso clínico"),
                array("id" => "008", "subject_id" => "3", "order" => "008", "instructions" => "Responda el siguiente caso clínico"),
                array("id" => "009", "subject_id" => "3", "order" => "009", "instructions" => "Responda el siguiente caso clínico"),
                array("id" => "010", "subject_id" => "3", "order" => "010", "instructions" => "Responda el siguiente caso clínico"),
                array("id" => "011", "subject_id" => "3", "order" => "011", "instructions" => "Responda el siguiente caso clínico"),
                array("id" => "012", "subject_id" => "4", "order" => "012", "instructions" => "Responda el siguiente caso clínico"),
                array("id" => "013", "subject_id" => "4", "order" => "013", "instructions" => "Responda el siguiente caso clínico"),
                array("id" => "014", "subject_id" => "4", "order" => "014", "instructions" => "Responda el siguiente caso clínico"),
                array("id" => "015", "subject_id" => "4", "order" => "015", "instructions" => "Responda el siguiente caso clínico"),
                array("id" => "016", "subject_id" => "4", "order" => "016", "instructions" => "Responda el siguiente caso clínico"),
                array("id" => "017", "subject_id" => "5", "order" => "017", "instructions" => "Responda el siguiente caso clínico"),
                array("id" => "018", "subject_id" => "5", "order" => "018", "instructions" => "Responda el siguiente caso clínico"),
                array("id" => "019", "subject_id" => "5", "order" => "019", "instructions" => "Responda el siguiente caso clínico"),
                array("id" => "020", "subject_id" => "5", "order" => "020", "instructions" => "Responda el siguiente caso clínico"),
                array("id" => "021", "subject_id" => "5", "order" => "021", "instructions" => "Responda el siguiente caso clínico"),
                array("id" => "022", "subject_id" => "5", "order" => "022", "instructions" => "Responda el siguiente caso clínico"),
                array("id" => "023", "subject_id" => "5", "order" => "023", "instructions" => "Responda el siguiente caso clínico"),
                array("id" => "024", "subject_id" => "5", "order" => "024", "instructions" => "Responda el siguiente caso clínico"),
                array("id" => "025", "subject_id" => "6", "order" => "025", "instructions" => "Responda el siguiente caso clínico"),
                array("id" => "026", "subject_id" => "6", "order" => "026", "instructions" => "Responda el siguiente caso clínico"),
                array("id" => "027", "subject_id" => "6", "order" => "027", "instructions" => "Responda el siguiente caso clínico"),
                array("id" => "028", "subject_id" => "7", "order" => "028", "instructions" => "Responda el siguiente caso clínico"),
                array("id" => "029", "subject_id" => "7", "order" => "029", "instructions" => "Responda el siguiente caso clínico"),
                array("id" => "030", "subject_id" => "8", "order" => "030", "instructions" => "Responda el siguiente caso clínico"),
                array("id" => "031", "subject_id" => "8", "order" => "031", "instructions" => "Responda el siguiente caso clínico"),
                array("id" => "032", "subject_id" => "8", "order" => "032", "instructions" => "Responda el siguiente caso clínico"),
                array("id" => "033", "subject_id" => "9", "order" => "033", "instructions" => "Responda el siguiente caso clínico"),
                array("id" => "034", "subject_id" => "9", "order" => "034", "instructions" => "Responda el siguiente caso clínico"),
                array("id" => "035", "subject_id" => "9", "order" => "035", "instructions" => "Responda el siguiente caso clínico"),
                array("id" => "036", "subject_id" => "9", "order" => "036", "instructions" => "Responda el siguiente caso clínico"),
                array("id" => "037", "subject_id" => "9", "order" => "037", "instructions" => "Responda el siguiente caso clínico"),
                array("id" => "038", "subject_id" => "9", "order" => "038", "instructions" => "Responda el siguiente caso clínico"),
                array("id" => "039", "subject_id" => "10", "order" => "039", "instructions" => "Responda el siguiente caso clínico"),
                array("id" => "040", "subject_id" => "10", "order" => "040", "instructions" => "Responda el siguiente caso clínico"),
                array("id" => "041", "subject_id" => "10", "order" => "041", "instructions" => "Responda el siguiente caso clínico"),
                array("id" => "042", "subject_id" => "10", "order" => "042", "instructions" => "Responda el siguiente caso clínico"),
                array("id" => "043", "subject_id" => "10", "order" => "043", "instructions" => "Responda el siguiente caso clínico"),
                array("id" => "044", "subject_id" => "11", "order" => "044", "instructions" => "Responda el siguiente caso clínico"),
                array("id" => "045", "subject_id" => "11", "order" => "045", "instructions" => "Responda el siguiente caso clínico"),
                array("id" => "046", "subject_id" => "11", "order" => "046", "instructions" => "Responda el siguiente caso clínico"),
                array("id" => "047", "subject_id" => "11", "order" => "047", "instructions" => "Responda el siguiente caso clínico"),
                array("id" => "048", "subject_id" => "12", "order" => "048", "instructions" => "Responda el siguiente caso clínico"),
                array("id" => "049", "subject_id" => "12", "order" => "049", "instructions" => "Responda el siguiente caso clínico"),
                array("id" => "050", "subject_id" => "12", "order" => "050", "instructions" => "Responda el siguiente caso clínico"),
                array("id" => "051", "subject_id" => "13", "order" => "051", "instructions" => "Responda el siguiente caso clínico"),
                array("id" => "052", "subject_id" => "14", "order" => "052", "instructions" => "Responda el siguiente caso clínico"),
                array("id" => "053", "subject_id" => "14", "order" => "053", "instructions" => "Responda el siguiente caso clínico"),
                array("id" => "054", "subject_id" => "14", "order" => "054", "instructions" => "Responda el siguiente caso clínico"),
                array("id" => "055", "subject_id" => "15", "order" => "055", "instructions" => "Responda el siguiente caso clínico"),
                array("id" => "056", "subject_id" => "15", "order" => "056", "instructions" => "Responda el siguiente caso clínico"),
                array("id" => "057", "subject_id" => "15", "order" => "057", "instructions" => "Responda el siguiente caso clínico"),
                array("id" => "058", "subject_id" => "15", "order" => "058", "instructions" => "Responda el siguiente caso clínico"),
                array("id" => "059", "subject_id" => "16", "order" => "059", "instructions" => "Responda el siguiente caso clínico"),
                array("id" => "060", "subject_id" => "16", "order" => "060", "instructions" => "Responda el siguiente caso clínico")
            );


        foreach ($slots as $slot) {
            EMMA5\Slot::create($slot);
        }

        $vignettes = array(
            array('text' => 'Hombre de 28 años albañil quien se cayó de 5 metros de altura y presentó traumatismo cráneo-encefálico. Referido de otro hospital, ingresa con ropas orinadas; presenta vómitos, crisis convulsivas tónico-clónicas, mucosas secas, temperatura 38.5º C y Glasgow de 10. Na 160 mEq/L, K 3.4 mEq/L y Cl 116 mEq/L, CO<sub>2</sub>T 18 mmol/L y pCO<sub>2</sub> 25. EGO: pH 6.5 y densidad 1.003.','slot_id' => '001', 'order' => '001', 'instructions' => 'Responda analice este caso clínico y responda las preguntas'),
            array('text' => 'Mujer de 72 años con hipertensión arterial tratada con losartán, por descontrol hipertensivo se agrega hidroclorotiazida. Una semana después presenta dificultad para la marcha, confusión y somnolencia. EF: TA 130/70 mm Hg, bien hidratada sin deficit neurológico focal ni edema. Glucosa 100 mg/dL, BUN 14 mg/dL, creatinina 0.9 mg/dL y ácido úrico 4.5 mg/dL. Cl 80 mEq/L, K 3.2 mEq/L y Na 104 mEq/L. EGO: pH 5.5. Na<sub>U</sub> 120 mEq/L y Uosm 300 mosmol/L.','slot_id' => '002', 'order' => '001', 'instructions' => 'Responda analice este caso clínico y responda las preguntas'),
            array('text' => 'Hombre de 45 años quien desde hace 1 año presenta hipertensión arterial. En 2 ocasiones se ha presentado al servicio de urgencias por crisis hipertensiva. Se le internó durante 2 semanas en nefrología para estudio. Na 140 mEq/L, K 2 mEq/L. K<sub>U</sub> 80 mEq/L. Posm 290 mOsm/L y Uosm 580 mOsm/L. Examen general de orina normal','slot_id' => '003', 'order' => '001', 'instructions' => 'Responda analice este caso clínico y responda las preguntas'),
            array('text' => 'Hombre de 55 años diabético e hipertenso, quien toma IECA, ARA<sub>2</sub>, ácido acetilsalicílico y furosemide. Presenta edema +++ en miembros inferiores por lo que le indican espironolactona 25 mg/día. Ingresa con FC 44 x\', TA 80/50 mm Hg, pálido, somnoliento y diaforético. K 8.1, Na 135 mEq/dL, creatinina 2.5 mg/dL y BUN 55 mg/dL.','slot_id' => '004', 'order' => '001', 'instructions' => 'Responda analice este caso clínico y responda las preguntas'),
            array('text' => 'Hombre de 71 años con ataque al estado general progresivo, dolor lumbar y pérdida de 8 kg de peso en los últimos 3 meses. TA 140/90 mm Hg. Hb 8 g/dL. Proteínas totales 8 g/L. Ca 11 mg/dL, fosfatasa alcalina 420 UI/L, BUN 54 mg/dL, creatinina 2.4 mg/dL y ácido úrico 8.6 mg/dL. EGO: proteínas +, glucosa negativa, leucocitos 2 y eritrocitos 4 por campo.','slot_id' => '005', 'order' => '001', 'instructions' => 'Responda analice este caso clínico y responda las preguntas'),
            array('text' => 'Mujer de 53 años con DM en DPCA desde hace 3 años. Acude con fiebre, necrosis dolorosa en dedo medio de mano y úlcera en pierna que no cicatriza. TA 140/100 mm Hg, FC 90 x\', BUN 77 mg/dL, creatinina 10 mg/dL, albúmina 3.5 mg/dL, Ca 10.8 mg/dL, PO<sub>4</sub> 11 mg/dL y PTH 650 pg/mL. Se muestra Rx de mano y biopsia de piel.','slot_id' => '006', 'order' => '001', 'instructions' => 'Responda analice este caso clínico y responda las preguntas'),
            array('text' => 'Hombre de 60 años diabético e hipertenso desde hace 20 años; inició hace 8 semanas diálisis peritoneal continua ambulatoria con 4 recambios al día de 2 litros cada uno, alternando soluciones al 2.5 y 4.25 % de dextrosa. Presenta edema de miembros pélvicos ++++, edema bipalpebral, disnea de grandes y medianos esfuerzos. EF: TA 160/100 mm Hg y FC 102 x\'. Hb 7.5 g/dL, BUN 60 mg/dL y creatinina 8 mg/dL. Albúmina 3.5 g/dL, Ca 7.5 mg/dL y PO<sub>4</sub> 8 mg/dL. CO<sub>2</sub>T 23 mEq/L.','slot_id' => '007', 'order' => '001', 'instructions' => 'Responda analice este caso clínico y responda las preguntas'),
            array('text' => 'Mujer de 45 años en programa de DPA desde hace 1 año con 12 litros por día al 2.5%. Su UF en 24 horas es de 1,750 cc. EF: TA 140/95 mm Hg, FC 90 x\', peso 58 kg y talla 1.65 m; sin edema. En la Rx de tórax se observa cardiomegalia grado II/IV. La relación D/PCr a las 2 horas 0.3. BUN 130 mg/dL, creatinina 17 mg/dL y K 6.3 mEq/L.','slot_id' => '008', 'order' => '001', 'instructions' => 'Responda analice este caso clínico y responda las preguntas'),
            array('text' => 'Mujer de 45 años con DPA desde hace 4 años. Inició hace 3 días con dolor abdominal, náusea y fiebre. EF: TA 100/60 mm Hg, FC 88 x\', FR 23 x\', temp 38º C y palidez generalizada; en la salida del catéter Tenckhoff se observa secreción fétida de color amarillo. Dolor abdominal y signo de rebote. Leucocitos 17,000/mm<sup>3</sup> con predominio de polimorfonucleares. Hb 9.3 g/dL, BUN 50 mg/dL y creatinina 6 mg/dL. Citológico de líquido de diálisis con 800 leucocitos y 80% neutrófilos.','slot_id' => '009', 'order' => '001', 'instructions' => 'Responda analice este caso clínico y responda las preguntas'),
            array('text' => 'Hombre de 65 años con DPCA, quien desde hace 2 días presenta líquido de diálisis turbio, náusea, vómitos y dolor abdominal. EF: TA 140/90 mm Hg, FC 70 x\', temp 37.6º C y FR 18 x\'. Abdomen doloroso a la palpación profunda; sin datos de irritación peritoneal.','slot_id' => '010', 'order' => '001', 'instructions' => 'Responda analice este caso clínico y responda las preguntas'),
            array('text' => 'Hombre de 68 años, diabético de larga evolución con retinopatía proliferativa avanzada y amputación supracondílea de miembro pélvico derecho; en DPCA desde hace 3 años. Refiere astenia, adinamia, anorexia, plenitud posprandial, náusea, vómito y debilidad muscular. Peso 65 kg, talla 168 cm, TA 130/90 mm Hg, edema ++, palidez ++ y pérdida de masa muscular. Hb 8.7 g/dL, ferritina 450 ng/mL, % saturación de trasferrina 12, glucosa 145 mg/dL, BUN 55 mg/dL, creatinina 5.5 mg/dL, albúmina 1.8 g/dL, PO<sub>4</sub> 6.0 mg/dL, Ca 6.0 mg/dL e índice catabólico proteico 0.5 g/kg/día.','slot_id' => '011', 'order' => '001', 'instructions' => 'Responda analice este caso clínico y responda las preguntas'),
            array('text' => 'Hombre de 48 años con antecedente de infección de vías respiratorias altas en el último año y desde hace 6 meses presenta edema en miembros pélvicos. EF: TA 110/70 mm Hg; hipoventilación basal bilateral y ascitis +++. Proteínas en orina de 24 horas 10 g, albúmina plasmática 2.1 mg/dL, colesterol 420 mg/dL y creatinina 1.6 mg/dL. Se toma biopsia renal.','slot_id' => '012', 'order' => '001', 'instructions' => 'Responda analice este caso clínico y responda las preguntas'),
            array('text' => 'Mujer de 18 años con lipodistrofia parcial en tronco y hematuria macroscópica recurrente. Antecedente de síndrome nefrótico, hipertensión e hipocomplementemia a los 14 años; no recibió tratamiento. Actualmente creatinina de 3 mg/dL.','slot_id' => '013', 'order' => '001', 'instructions' => 'Responda analice este caso clínico y responda las preguntas'),
            array('text' => 'Mujer de 45 años quien inició hace 1 mes con edema de miembros inferiores. EF: TA 110/70 mm Hg. Proteínas en orina de 24 horas 18 g, albúmina sérica 1.5 g/dL, colesterol total 500 mg/dL y creatinina sérica 0.6 mg/dL.','slot_id' => '014', 'order' => '001', 'instructions' => 'Responda analice este caso clínico y responda las preguntas'),
            array('text' => 'Mujer de 18 años quien inició hace 3 meses con edema periorbitario y en miembros pélvicos. Proteínas en orina de 24 horas de 4 g/día, albúmina sérica 2.5 g/dL, colesterol total 250 mg/dL y creatinina sérica 1.6 mg/dL. Sedimento urinario irrelevante. EF: TA 180/110 mm Hg.','slot_id' => '015', 'order' => '001', 'instructions' => 'Responda analice este caso clínico y responda las preguntas'),
            array('text' => 'Hombre de 25 años quien ha presentado en 3 ocasiones hematuria macroscópica posterior a infección de vías aéreas superiores. Se presenta por hematuria macroscópica y disuria. EF: TA 130/75 mm Hg, faringe hiperémica + sin exudados. Creatinina 1.0 mg/dL, BUN 12 mg/dL. EGO: pH 6.0, densidad 1.030, proteínas 0.8 g/día, nitritos -, leucocitos 1 a 2 por campo y eritrocitos incontables. C3 90 mg/dL (N 80-120).','slot_id' => '016', 'order' => '001', 'instructions' => 'Responda analice este caso clínico y responda las preguntas'),
            array('text' => 'Mujer de 55 años, empleada en empresa curtidora de pieles, quien desde hace 4 días presenta ataque severo al estado general y hemoptisis. TA 160/110 mm Hg y edema de miembros pélvicos. Creatinina 7 mg/dL, anticuerpos antinucleares negativos, hematuria y proteinuria ++++. Por ultrasonido riñones de tamaño normal. Se practicó biopsia renal.','slot_id' => '017', 'order' => '001', 'instructions' => 'Responda analice este caso clínico y responda las preguntas'),
            array('text' => 'Mujer de 18 años quien presentó hace 14 días infección de vías respiratorias altas. Inició hace 2 días con edema palpebral matutino, orina oscura y oliguria. EF: FC 102 x\', TA 150/98 mm Hg, palidez ++, edema facial ++ y edema en miembros pélvicos ++. Hb 10 g/dL y leucocitos 8,200/mm<sup>3</sup>. Creatinina 2.3 mg/dL; C3 bajo y AAN negativo. EGO: proteínas ++, eritrocitos incontables, leucocitos 10 por campo, cilindros hemáticos y granulosos.','slot_id' => '018', 'order' => '001', 'instructions' => 'Responda analice este caso clínico y responda las preguntas'),
            array('text' => 'Hombre de 67 años previamente sano quien inició hace 2 semanas con ataque al estado general, vómitos, diarrea e hipertermia; y hace 3 días se agregan edema, hipertensión y hematuria; tratado con aminoglucósidos y antipiréticos. Creatinina 3.6 mg/dL y proteínas 1.5 g en orina de 24 horas. EGO: hemoglobina +++, proteínas ++; se muestra sedimento.','slot_id' => '019', 'order' => '001', 'instructions' => 'Responda analice este caso clínico y responda las preguntas'),
            array('text' => 'Hombre de 18 años quien inició hace 3 días con malestar general. EF: petequias, palidez, oliguria, temperatura 37.2 C, FC 130 x\', FR 26 x\' y TA 130/90 mm Hg. Hb 6.2 g/dL, leucocitos 23,000/mm<sup>3</sup> con 60% neutrófilos y 8% de bandas. Plaquetas 42,000/?L. En sangre periférica esquistocitos. TP 11 seg y TPT 30 seg. K 5.8 mEq/L, Cl 100 mEq/L, HCO<sub>3</sub> 13 mEq/L; BUN 80 mg/dL y creatinina 3.4 mg/dL. C3 96 y C421. EGO: albúmina +, hemoglobina +, acetona +, escasas bacterias y cilindros eritrocitarios.','slot_id' => '020', 'order' => '001', 'instructions' => 'Responda analice este caso clínico y responda las preguntas'),
            array('text' => 'Hombre de 39 años con infecciones de vías respiratorias superiores, sinusitis frontal, maxilar y etmoidal de repetición. Desde hace un año se le ha detectado hematuria microscópica y en 3 ocasiones proteinuria +; hace 1 mes se agrega tos con expectoración blanquecina intermitente. EF: TA 140/90 mm Hg, mucosa nasal eritematosa, campos pulmonares con estertores gruesos bilaterales diseminados. Creatinina 3.2 mg/dL, Hb 11 g/dL, leucocitos 12,000/mm<sup>3</sup> y plaquetas 480,000/mm<sup>3</sup>.','slot_id' => '021', 'order' => '001', 'instructions' => 'Responda analice este caso clínico y responda las preguntas'),
            array('text' => 'Mujer de 25 años quien inició hace 4 meses con caída de cabello, edema palpebral matutino intermitente, artralgias en rodillas y tobillos. EF: TA 180/110 mm Hg, dolor y edema ++ en miembro pélvico derecho. Hb 9 g/dL, leucocitos 3,800/mm<sup>3</sup>, plaquetas 80,000/mm<sup>3</sup>, creatinina 1.4 mg/dL y albúmina 3.6 g/dL. EGO: leucocitos 10 y eritrocitos 40 por campo. Proteinuria de 800 mg/24 horas. TP 15 seg y TPT 50 seg. Se establece el diagnóstico de lupus eritematoso sistémico.','slot_id' => '022', 'order' => '001', 'instructions' => 'Responda analice este caso clínico y responda las preguntas'),
            array('text' => 'Hombre de 42 años quien desde hace 3 años presenta infecciones frecuentes, pérdida de peso y hace 6 meses se agrega edema generalizado. EF: peso 54 kg, talla 176 cm, TA 140/95 mm Hg, palidez ++, edema generalizado, lesiones blanquecinas en mucosa oral y úlceras en piel. Hb 12 g/dL, creatinina 2.7 mg/dL, albúmina 1.2 g/dL, colesterol 500 mg/dL y triglicéridos 300 mg/dL. Proteínas en orina de 24 horas 12 g. CD<sub>4</sub> 160. Antiestreptolisinas 200 U Todd.','slot_id' => '023', 'order' => '001', 'instructions' => 'Responda analice este caso clínico y responda las preguntas'),
            array('text' => 'Mujer de 22 años quien posterior a infección de vías aéreas superiores inicia con dolor abdominal, artralgias y lesiones purpúricas en extremidades inferiores y glúteos; orina obscura y melena. EF: TA 140/90 mm Hg y edema palpebral. Plaquetas 200,000/mm<sup>3</sup>, albúmina sérica 3 g/dL y creatinina 1.6 mg/dL. EGO: eritrocitos abundantes y cilindros hemáticos. Proteínas 4 g en orina de 24 horas.','slot_id' => '024', 'order' => '001', 'instructions' => 'Responda analice este caso clínico y responda las preguntas'),
            array('text' => 'Adolescente masculino de 16 años con síndrome de Alport. General de orina con eritrocitos 8 a 10 por campo, plaquetas 500,000/mm<sup>3</sup>, creatinina sérica 1.8 mg/dL, depuración de creatinina de 55 mL/min y proteínas en orina de 24 horas 400 mg.','slot_id' => '025', 'order' => '001', 'instructions' => 'Responda analice este caso clínico y responda las preguntas'),
            array('text' => 'Hombre de 30 años con acroparestesias e hipohidrosis evaluado por elevación de creatinina. Madre con diagnóstico de proteinuria no nefrótica. EF: TA 140/90 mm Hg y FC 68 x\'; hepatomegalia, manchas hiperpigmentadas y edema en miembros pélvicos. Hemoglobina 8 g/dL, creatinina 5.0 mg/dL, albúmina sérica 2.8 g/dL; complemento normal; serología para hepatitis y VIH negativos. Albuminuria/creatinuria 5 g/g. Rx de tórax con cardiomegalia grado III/IV. Se practicó biopsia renal.','slot_id' => '026', 'order' => '001', 'instructions' => 'Responda analice este caso clínico y responda las preguntas'),
            array('text' => 'Hombre de 18 años con un hermano que presentó a los 15 años de edad enfermedad renal crónica avanzada. Inició hace 1 año con nicturia, poliuria y palidez. Hb 8 g/dL, creatinina 7 mg/dL, Ca 7.5 mg/dL, K 4 mEq/L, Cl 103 mEq/L y HCO<sub>3</sub> 15 mEq/L. EGO: densidad 1.007, glucosa +, proteína ++ y 10 leucocitos por campo. US: riñones de 8 cm con pérdida de relación cortico-medular.','slot_id' => '027', 'order' => '001', 'instructions' => 'Responda analice este caso clínico y responda las preguntas'),
            array('text' => 'Adolescente femenina de 15 años con antecedente de infecciones urinarias de repetición desde la infancia; acude con fiebre y urosepsis. TA 80/50 mm Hg. Giordano positivo bilateral. Leucocitos 20,000/mm<sup>3</sup>, creatinina 2.7 mg/dL y BUN 32 mg/dL. EGO: leucocitos incontables, hemoglobina +++ y proteínas ++.','slot_id' => '028', 'order' => '001', 'instructions' => 'Responda analice este caso clínico y responda las preguntas'),
            array('text' => 'Hombre de 75 años quien inició hace 2 meses con ataque al estado general, pérdida de peso no cuantificada, dolor abdominal, fiebre y poliaquiuria EF: TA 140/90 mm Hg, temp 37.5º C, abdomen con masa dolorosa en hipogastrio, extremidades inferiores con edema ++. Hb 8.5 mg/dL, plaquetas 550,000/mm<sup>3</sup>, leucocitos 13,200/mm<sup>3</sup>, creatinina 6.4 mg/dL, K 6.8 mEq/dL, TGO 25 UI/L, TGP 15 UI/L, DHL 450 UI/L y ácido úrico 9 mg/dL.','slot_id' => '029', 'order' => '001', 'instructions' => 'Responda analice este caso clínico y responda las preguntas'),
            array('text' => 'Mujer de 30 años con embarazo de 38 semanas, quien presenta desprendimiento prematuro de placenta normoinserta complicada con estado de choque; se somete a cesárea de urgencia, en el posoperatorio presenta anuria, se le dió manejo con hemodiálisis y antibióticos por infección de vías urinarias por Escherichia coli. Creatinina 7 mg/dL. Después de 8 semanas continua con hemodiálisis y volúmenes urinarios entre 400-600 mL/24 h con creatinina entre 6 a 8 mg/dL. En este momento se le realiza ultrasonido.','slot_id' => '030', 'order' => '001', 'instructions' => 'Responda analice este caso clínico y responda las preguntas'),
            array('text' => 'Mujer de 17 años primigesta, con embarazo de 30 semanas, quien presenta desde hace 15 días cefalea y edema de miembros pélvicos. TA 150/90 mm Hg. EGO: proteínas 300 mg/dL, eritrocitos 3 por campo y leucocitos 5 por campo, creatinina 0.7 mg/dL y BUN 8 mg/dL. Fondo de ojo normal. Recibió esteroide y en la semana 32 se le realiza cesárea.','slot_id' => '031', 'order' => '001', 'instructions' => 'Responda analice este caso clínico y responda las preguntas'),
            array('text' => 'Mujer de 19 años, primigesta, con embarazo de 14 semanas. Inició hace 3 días con edema ++++ de miembros inferiores hasta medio muslo y presión arterial de 160/104 mm Hg. Exámenes a su ingreso: creatinina sérica 0.5 mg/dL, urea 30 mg/dL, ácido úrico 5 mg/dL, colesterol 356 mg/dL, triglicéridos 413 mg/dL y albúmina 1.8 g/dL. EGO: proteínas 300 mg/dL, glucosa 30 mg/dL y sedimento irrelevante. ANA 1:80, C3 y C4normales. En orina de 24 horas 16 g de proteínas. US renal normal.','slot_id' => '032', 'order' => '001', 'instructions' => 'Responda analice este caso clínico y responda las preguntas'),
            array('text' => 'Mujer de 35 años en hemodiálisis desde hace 1 año a través catéter yugular. Se le realizó fístula radio-cefálica en antebrazo izquierdo y después de 5 meses no ha desarrollado suficiente flujo, los primeros 6 a 8 cm de la fístula son palpables y pulsan; el thrill en la anastomosis apenas es perceptible y no mejora cuando se ocluye.','slot_id' => '033', 'order' => '001', 'instructions' => 'Responda analice este caso clínico y responda las preguntas'),
            array('text' => 'Mujer de 58 años con nefropatía diabética en hemodiálisis desde hace 8 meses; 3 horas 2 veces por semana con flujo sanguíneo de 240 mL/min y ultrafiltración a un peso de 76 kg. Insulina 10 UI/día, nifedipino 60 mg/día, furosemida 120 mg/día, enalapril 20 mg/día y prazocina 3 mg/día. EF: TA 210/130 mm Hg y FC 104 x\'; edema en miembros inferiores ++. Hb 10 g/dL. Creatinina 15 mg/dL y K 6.5 mEq/L. Diuresis 600 mL/24 horas. En la Rx de tórax se observa cardiomegalia grado III/IV y congestión pulmonar. Ecocardiograma con hipertrofia ventricular izquierda excéntrica.','slot_id' => '034', 'order' => '001', 'instructions' => 'Responda analice este caso clínico y responda las preguntas'),
            array('text' => 'Mujer de 18 años en hemodiálisis desde hace 7 años. Multitransfundida. HBsAg positivo y HBc Ac-IgM positivo (core). Carga viral 500,000 copias/mL.','slot_id' => '035', 'order' => '001', 'instructions' => 'Responda analice este caso clínico y responda las preguntas'),
            array('text' => 'Hombre de 68 años diabético con insuficiencia cardiaca decompensada, choque cardiogénico y oligo-anuria. TA 70/30 mm Hg, FC 111 x\', FR 28 x\', saturación 88% en ventilación mecánica no invasiva. BUN 111 mg/dL, creatinina 6 mg/dL y K 6.3 mEq/L. En tratamiento con dopamina, dobutamina y norepinefrina.','slot_id' => '036', 'order' => '001', 'instructions' => 'Responda analice este caso clínico y responda las preguntas'),
            array('text' => 'Mujer de 35 años en hemodiálisis 2 veces por semana desde hace 3 años con KT/V 2.5. Actualmente con anuria. Exámenes actuales: ácido úrico 6.6 mg/dL, albúmina 3.4 g/dL, colesterol 150 mg/dL, triglicéridos 104 mg/dL, Hb 8.2 mg/dL, VCM 93, CMH 31, reticulocitos 1%, plaquetas 97,000/mm<sup>3</sup>, ferritina 400 ng/mL, capacidad de fijación 299 y saturación de transferrina 30%; fosfatasa alcalina 74 UI/L, BUN 89 mg/dL, creatinina 11.7 mg/dL, Ca 8.4 mg/dL, PO<sub>4</sub> 7.9 mg/dL y K 5.3 mEq/L. PTH 230 pg/mL. PCR 1 mg/L.','slot_id' => '037', 'order' => '001', 'instructions' => 'Responda analice este caso clínico y responda las preguntas'),
            array('text' => 'Mujer de 21 años en hemodiálisis; ha recibido múltiples hemotransfusiones. A su ingreso VIH, AgsHB y ac-VHC negativos. Tres meses después de iniciada la hemodiálisis presenta Hb 8.5 g/dL, TGO 84 UI/L y TGP 62 UI/L, sin ictericia. Las transaminasas mejoran espontáneamente. Recibió esquema de vacunación contra virus B de hepatitis. Después de un año: AgsHB negativo, ac-VHC negativo, ac-AgsHB positivo y ac-IgG-AgHB core positivo. Recibió un injerto de donador fallecido. A partir de entonces se han documentado elevaciones transitorias de enzimas hepáticas. Se toma biopsia hepática. Ferritina 2,000 ng/mL.','slot_id' => '038', 'order' => '001', 'instructions' => 'Responda analice este caso clínico y responda las preguntas'),
            array('text' => 'Mujer de 24 años con TA de 180/110 mm Hg, debilidad generalizada, polidipsia y poliuria. Na 143 mEq/L, K 2.3 mEq/L, Cl 100 mEq/L y CO<sub>2</sub> T 32 mEq/L. K<sub>U</sub> 45 mEq/L.','slot_id' => '039', 'order' => '001', 'instructions' => 'Responda analice este caso clínico y responda las preguntas'),
            array('text' => 'Mujer de 74 años hipertensa con cifras de 180/115 mm Hg en múltiples ocasiones. Súbitamente inicia con cefalea intensa, vómito, alteraciones visuales y convulsiones. EF: TA 230/136 mm Hg, FC 90 x\', FR 32 x\', pálida, diaforética, sin respuesta al estímulo verbal y galope auricular.','slot_id' => '040', 'order' => '001', 'instructions' => 'Responda analice este caso clínico y responda las preguntas'),
            array('text' => 'Mujer de 34 años quien inició hace 2 semanas con episodios de cefalea, mareo, sensación de bochornos, disnea y palpitaciones que se incrementan durante el ejercicio. Hoy por la mañana se agregan escotomas en ojo izquierdo que desaparecieron a los 35 minutos después de reposo. TA 170/120 mm Hg y FC 96 x\'.','slot_id' => '041', 'order' => '001', 'instructions' => 'Responda analice este caso clínico y responda las preguntas'),
            array('text' => 'Mujer de 19 años con hipertensión arterial de un año de evolución de difícil control. Tabaquismo intenso. Acude por cefalea y palpitaciones. TA 180/110 mm Hg y FC 84 x\'. Pulsos periféricos normales. K 2.9 mEq/L, Na 143 mEq/L, Ca 9.2 mg/dL y PO<sub>4</sub> 3.8 ng/dL.','slot_id' => '042', 'order' => '001', 'instructions' => 'Responda analice este caso clínico y responda las preguntas'),
            array('text' => 'Mujer de 28 años sin antecedentes familiares de importancia. Inició hace 4 meses con TA 180/120 mm Hg, incremento de peso a expensas del perímetro abdominal, estrías cutáneas y acné facial. En la evaluación inicial TA 160/110 mm Hg (confirmada en tres ocasiones), FC 88 x\', FR 18 x\', peso 90 kg y talla 1.62 m. El fondo de ojo es normal.','slot_id' => '043', 'order' => '001', 'instructions' => 'Responda analice este caso clínico y responda las preguntas'),
            array('text' => 'Mujer de 19 años quien hace 5 días recibió quimioterapia. Desde hace 24 horas presenta dolor abdominal, temblor distal fino e hiperreflexia. EF: TA 100/60 mm Hg y oliguria. Creatinina sérica 3.8 mg/dL, Na 136 mEq/dL, K 6.2 mEq/L, PO<sub>4</sub> 11.8 ng/dL, DHL 3,399 UI/L, Ca 5.1 mg/dL y Mg 1.5 mg/dL. Examen de orina: pH 5.5, densidad 1.027 y proteínas 30 mg/dL; leucocitos 3 por campo y eritrocitos 1 por campo.','slot_id' => '044', 'order' => '001', 'instructions' => 'Responda analice este caso clínico y responda las preguntas'),
            array('text' => 'Adolescente femenina de 18 años, con anorexia nervosa y abuso de diuréticos. Participó en medio maratón. Presenta TA 80/40 mm Hg, FC 100 x\', dolor muscular generalizado, mucosas secas. Volumen urinario disminuido. Creatinina 3.5 mg/dL, urea 240 mg/dL, K 2.2 mEq/L, Na 132 mEq/L y Mg 1.5 mEq/L. CPK 15,000 UI/L. EGO: orina color café obscuro, proteína +, sangre +++ y K<sub>U</sub> 55 mEq/L. Se muestra sedimento urinario.','slot_id' => '045', 'order' => '001', 'instructions' => 'Responda analice este caso clínico y responda las preguntas'),
            array('text' => 'Mujer de 82 años diabética con urosepsis, hipertermia de 39º C, recibió gentamicina por 8 días y la creatinina se eleva de 1.3 a 4 mg/dL, BUN 60 y Na sérico 142 mEq/L. Hb 12 mg/dL, leucocitos 14,500/mm<sup>3</sup> y plaquetas 350,000/m3. Los azoados no mejoran con hidratación. Diuresis 1mL/kg/hora. Se muestra sedimento.','slot_id' => '046', 'order' => '001', 'instructions' => 'Responda analice este caso clínico y responda las preguntas'),
            array('text' => 'Mujer de 55 años diabética desde hace 10 años con mal control y artropatía crónica automedicada con altas dosis de AINEs. Presenta desde hace 5 días dolor lumbar izquierdo de inicio súbito, intenso, tipo cólico, náusea y vómito. Orina con hematuria, abundante sedimento y fragmentos de tejido friable. Hb 11 g/dL, Hto 33 %, leucocitos 9,500/mm<sup>3</sup> y plaquetas 150,000/µL. Glucosa 300 mg/dL y creatinina sérica 1.9 mg/dL. Examen general de orina: leucocituria, proteinuria, glucosuria, eritrocituria y detritus. Urocultivo negativo.','slot_id' => '047', 'order' => '001', 'instructions' => 'Responda analice este caso clínico y responda las preguntas'),
            array('text' => 'Hombre de 40 años caquéctico con enfermedad renal crónica con depuración de creatinina de 11 mL/min; inició hace 3 meses con astenia, adinamia, disnea de pequeños esfuerzos y dolor óseo. EF: TA 150/100 mm Hg, FC 120 x\' y FR 20 x\'; ruidos cardíacos con ritmo de galope y soplo holositólico plurifocal y extremidades con edema ++. Hb 8.8 g/dL, Hto 25 %, VCM 90, CMH 30, plaquetas 234,000/?L. Albúmina sérica 2.5 g/dL, Ca 7.1 mg/dL, PO<sub>4</sub> 7 mg/dL, PTH 850 pg/mL. BUN 90 mg/dL y creatinina 4.8 mg/dL.','slot_id' => '048', 'order' => '001', 'instructions' => 'Responda analice este caso clínico y responda las preguntas'),
            array('text' => 'Mujer de 55 años, hipertensa y diabética tipo II de 15 años de evolución con control irregular. EF: TA 170/100 mm Hg. Glucosa 180 mg/dL, creatinina 2.5 mg/dL, hemoglobina glucosilada 8.9 %, proteínas totales 5.5 g/dL y albúmina 3.2 g/dL. Hb 10 g/dL. Ca 8.5 mg/dL y PO<sub>4</sub> 6.8 mg/dL. Ácido úrico 7.7 mg/dL, PTH 55 pg/L, colesterol 280 mg/dL, triglicéridos 235 mg/dL, filtración glomerular estimada 30 mL/min/1.73 m2 y proteínas 4.5 g en orina de 24 horas.','slot_id' => '049', 'order' => '001', 'instructions' => 'Responda analice este caso clínico y responda las preguntas'),
            array('text' => 'Mujer de 57 años con diabetes mellitus e hipertensión arterial de 17 años de evolución. Hace 4 años tuvo una creatinina sérica de 0.8 mg/dL. Actualmente tiene una TA de 150/90, IMC 29 kg/m2, retinopatía diabética e hipertensiva, y edema maleolar +. Actualmente: glicemia 198 mg/dL, nitrógeno de urea 35 mg/dL, creatinina 1.8 mg/dL, tasa estimada de filtración glomerular 31 mL/min/1.73 m2 SC. Hb 11 g/dL y Ca 8.9 mg/dL. EGO con proteinuria +, hemoglobina negativa, relación albúmina/creatinina en la primera muestra de orina de 340 mg/g.','slot_id' => '050', 'order' => '001', 'instructions' => 'Responda analice este caso clínico y responda las preguntas'),
            array('text' => 'Hombre de 45 años con cólico nefrítico y expulsión de lito hace 6 meses. EF: TA 140/90 mm Hg y peso 80 kg. Creatinina 1 mg/dL, ácido úrico sérico 6.0 mg/dL, BUN 15 mg/dL, Ca sérico 11.3 mg/dL, PO<sub>4</sub> sérico 1.9 mg/dL, UCa 350 mg/24 h, Uac úrico 500 mg/24 h. Reabsorción tubular máxima de PO<sub>4</sub> 50%. pH urinario 5.5.','slot_id' => '051', 'order' => '001', 'instructions' => 'Responda analice este caso clínico y responda las preguntas'),
            array('text' => 'Mujer de 69 años que acude a urgencias por dolor lumbar, fiebre y hematuria.','slot_id' => '052', 'order' => '001', 'instructions' => 'Responda analice este caso clínico y responda las preguntas'),
            array('text' => 'Mujer de 17 años con diabetes mellitus tipo 1 desde hace 5 años, en tratamiento con insulina lispro y NPH. Presenta albuminuria de 80 mg/día y HbA1c 8.5%.','slot_id' => '053', 'order' => '001', 'instructions' => 'Responda analice este caso clínico y responda las preguntas'),
            array('text' => 'Mujer de 64 años, con diabetes mellitus tipo 2 desde hace 16 años, obesidad y diagnóstico reciente de angina estable y descontrol hipertensivo en tratamiento con metformina, captopril, metoprolol y ácido acetilsalicílico. Proteinuria de 2.2 g/24 h; filtración glomerular calculada 40 mL/min y glucemia sérica en ayuno de 180 mg/dL.','slot_id' => '054', 'order' => '001', 'instructions' => 'Responda analice este caso clínico y responda las preguntas'),
            array('text' => 'Mujer de 36 años, quien 2 meses después de un trasplante renal exitoso de donante fallecido, se presenta con fiebre, disnea, leucopenia severa y elevación de aminotransferasas. Su tratamiento inmunosupresor había sido inducción con timoglobulina; actualmente con tacrolimus 3 mg/12 h, prednisona 5 mg/día y mofetil micofenolato 500 mg/8 h.','slot_id' => '055', 'order' => '001', 'instructions' => 'Responda analice este caso clínico y responda las preguntas'),
            array('text' => 'Hombre de 20 años quien recibió trasplante de donador vivo relacionado hace 1 año; tratado con prednisona, micofenolato de mofetilo y tacrolimus. Infección urinaria por Klebsiella a los 3 meses posterior al trasplante con aparente buena respuesta al tratamiento. Desde hace 2 meses la creatinina sérica se ha incrementado hasta 2 mg/dL. EF: TA 130/90 mm Hg y niveles de tacrolimus 10 ng/mL.','slot_id' => '056', 'order' => '001', 'instructions' => 'Responda analice este caso clínico y responda las preguntas'),
            array('text' => 'Mujer de 28 años con antecedente de nefritis lúpica, postrasplantada renal de donador vivo relacionado hace 3 años; esquema inmunosupresor con tacrolimus, micofenolato y prednisona. Creatinina sérica de 0.7 mg/dL y proteinuria de 200 mg día. Desea embarazarse.','slot_id' => '057', 'order' => '001', 'instructions' => 'Responda analice este caso clínico y responda las preguntas'),
            array('text' => 'Mujer de 40 años multípara en hemodiálisis desde hace 6 meses por enfermedad renal crónica de causa desconocida. Recibe trasplante renal del esposo. Prueba cruzada negativa: PRA 25% clase II. Inmunosupresión: tacrolimus, prednisona, mofetil micofenolato y anti-CD25. Evolución: diuresis inmediata, descenso de la creatinina hasta 1.8 mg en las primeras 48 horas, posteriormente disminución del volumen urinario, incremento en creatinina sérica hasta 4 mg/dL. Una semana después continúa con oligo-anuria, plaquetas 110,000/mm<sup>3</sup>. Nivel de tacrolimus 12 ng/mL.','slot_id' => '058', 'order' => '001', 'instructions' => 'Responda analice este caso clínico y responda las preguntas'),
            array('text' => 'Mujer de 35 años, quien presenta disminución progresiva de la fuerza muscular en miembros inferiores e incapacidad para deambular. Se detectó K+ sérico 1.5 mEq/L y se le administra KCl intravenoso y sales de potasio por vía oral subsecuentemente. EF: peso 59 kg. Gasometría arterial: pH 7.32, pCO<sub>2</sub> 28 mm Hg, HCO<sub>3</sub> 14 mEq/L. Na 138 mEq/L y Cl 115 mEq/L. Na<sub>U</sub> 110 mEq/L, K<sub>U</sub> 80 mEq/L, UCl 130 mEq/L y UCa 350 mg/24 h. pH urinario 6.0.','slot_id' => '059', 'order' => '001', 'instructions' => 'Responda analice este caso clínico y responda las preguntas'),
            array('text' => 'Mujer de 68 años con hipertensión nefropatía diabética. EF: TA 140/95 mm Hg y edema de extremidades pélvicas. BUN 40 mg/dL, creatinina sérica 1.4 mg/dL, Na 138 mEq/l, K 5.7 mEq/L, Cl 100 mEq/L y CO<sub>2</sub> 28 mEq/L. Fue tratada con captopril y restricción de sal. En los últimos 7 días se automedicó ibuprofeno. Tres días después presenta en urgencias con debilidad importante y mareo. BUN 50 mg/dL, creatinina sérica 1.9 mg/dL, Na 140 mEq/L, K 6.8 mEq/L, Cl 114 mEq/L y CO<sub>2</sub> 18 mEq/L. Gasometría venosa: pH 7.33, PCO<sub>2</sub> 33 y HCO<sub>3</sub> 18 mEq/L','slot_id' => '060', 'order' => '001', 'instructions' => 'Responda analice este caso clínico y responda las preguntas')
        );

        foreach ($vignettes as $vignette) {
            EMMA5\Vignette::create($vignette);
        }
    }
}
